from methodologies._base import REPORT, SCOPE, phases

INFRA_METHODOLOGIES = {
    "network/active-directory": phases(
        SCOPE + ["Obtain written AD test authorization and emergency contact"],
        ["Run BloodHound/SharpHound collection", "Enumerate users, groups, computers, GPOs", "Identify Kerberoastable and AS-REP roastable accounts", "Map trust relationships and ACL abuse paths"],
        ["Validate attack paths from low-priv user to DA", "Test Kerberoasting, NTLM relay, and ACL abuse", "Check for LLMNR/NBT-NS poisoning opportunities", "Review LAPS and tiered admin implementation"],
        ["Execute shortest path to Domain Admin in lab or approved window", "Demonstrate DCSync or Golden Ticket if in scope", "Document each hop with timestamps and tools", "Clean up created accounts and SPNs"],
        REPORT + ["Map findings to MITRE ATT&CK and BloodHound remediation"],
    ),
    "network/active-directory/kerberoasting": phases(
        SCOPE + ["Confirm low-priv domain user credentials available"],
        ["Enumerate SPNs with GetUserSPNs or Rubeus", "Request TGS tickets for service accounts", "Export hashes to crackable format", "Prioritize accounts without preauth or old passwords"],
        ["Crack RC4 tickets with hashcat rules", "Validate cracked password against service login", "Check if service account is over-privileged", "Test password reuse on other systems"],
        ["Demonstrate lateral movement with cracked service creds", "Document SPN account and cracked password policy", "Recommend gMSA and strong service passwords"],
        REPORT,
    ),
    "network/bloodhound": phases(
        SCOPE + ["Deploy SharpHound from domain-joined or credentialed host"],
        ["Collect ACL, session, and group data (all collection methods)", "Ingest JSON into BloodHound CE/legacy", "Review shortest paths to Domain Admins", "Identify high-value targets: Tier 0, unconstrained delegation"],
        ["Validate top 3 attack paths manually", "Check for kerberoastable paths to DA", "Export path details for reporting", "Re-run after remediation to verify fix"],
        ["Execute one path as proof if authorized", "Document nodes and edges in attack path", "Provide defensive Cypher queries for detection"],
        REPORT,
    ),
    "network/dcsync": phases(
        SCOPE + ["Confirm Replicating Directory Changes rights or equivalent"],
        ["Identify accounts with DCSync privileges via BloodHound", "Verify replication rights: GetChanges + GetChangesAll", "Prepare secretsdump command and output handling", "Ensure legal authorization for credential dump"],
        ["Execute DCSync against single high-value account first", "Validate NT hashes obtained", "Test pass-the-hash with extracted creds", "Avoid full domain dump unless required"],
        ["Demonstrate Golden Ticket or DA access from hash", "Securely store and destroy hash dumps after test", "Recommend tiered admin and protected users"],
        REPORT,
    ),
    "network/pentesting": phases(
        SCOPE + ["Define internal vs external test boundaries and stop conditions"],
        ["External: port scan, service enum, vulnerability scan", "Internal: host discovery, SMB/LDAP enum", "Identify default credentials and patch gaps", "Map network segmentation and trust zones"],
        ["Exploit critical vulns for initial access", "Capture credentials via responder or phishing (if in scope)", "Validate findings with manual exploitation", "Maintain access journal for client"],
        ["Demonstrate objective completion (DA, data access, segment crossing)", "Pivot through allowed segments only", "Avoid production disruption"],
        REPORT + ["Structure report by PTES phases with risk ratings"],
    ),
    "network/privilege-escalation/windows": phases(
        SCOPE + ["Establish low-priv shell on Windows target"],
        ["Run winPEAS and Watson for missing patches", "Check service permissions, unquoted paths, AlwaysInstallElevated", "Review token privileges (SeImpersonate, SeBackup)", "Hunt saved credentials and registry secrets"],
        ["Exploit identified misconfiguration or CVE", "Test potato-family privesc on SeImpersonate", "Validate admin/SYSTEM access", "Document exact binary and path abused"],
        ["Capture proof: whoami, hostname, admin groups", "Avoid installing persistent backdoors", "Recommend specific GPO and service hardening"],
        REPORT,
    ),
    "network/privilege-escalation/linux": phases(
        SCOPE + ["Obtain low-priv shell on Linux target"],
        ["Run linPEAS and linux-exploit-suggester", "Check sudo -l, SUID binaries, cron jobs, capabilities", "Review writable /etc/passwd and docker group", "Hunt SSH keys and credentials in configs"],
        ["Exploit SUID, sudo misconfig, or kernel CVE", "Validate root access with id and /root proof", "Check container breakout if on Docker host", "Document kernel version and exploit used"],
        ["Capture minimal root proof", "Clean up added users or keys", "Recommend patching and sudo hardening"],
        REPORT,
    ),
    "network/lateral-movement": phases(
        SCOPE + ["Document initial foothold host and credentials"],
        ["Identify reachable hosts from current position", "Spray or pass captured hashes (within ROE)", "Map admin shares and WinRM/SSH access", "Use CrackMapExec for enum and exec"],
        ["Validate access to next target with evil-winrm or psexec", "Capture new credentials from memory (if authorized)", "Track attack path for reporting", "Respect scope boundaries per host"],
        ["Demonstrate access to critical segment or server", "Stop at agreed objective (file server, DB, DC)", "Document each hop with tools and creds used"],
        REPORT,
    ),
    "network/wireless": phases(
        SCOPE + ["Confirm wireless test authorization and physical location"],
        ["Passively scan SSIDs, encryption, and clients", "Identify WPA2-PSK, WPA3, or enterprise networks", "Capture handshake or PMKID for offline crack", "Test evil twin and captive portal scenarios"],
        ["Crack weak PSK with aircrack-ng wordlist", "Test WPA enterprise cert validation", "Attempt MITM with bettercap after association", "Validate client isolation bypass"],
        ["Demonstrate network access from wireless compromise", "Document SSID, encryption, and crack time", "Recommend WPA3, strong PSK, and 802.1X"],
        REPORT,
    ),
    "network/firewall-segmentation": phases(
        SCOPE + ["Obtain network diagram and segmentation policy"],
        ["Probe allowed ports between zones with nmap/hping3", "Test default deny between DMZ and internal", "Identify overly permissive rules (any-any)", "Map paths from internet to crown jewels"],
        ["Validate bypass via dual-homed hosts", "Test management plane exposure", "Document each allowed flow with business justification", "Correlate with actual vs intended policy"],
        ["Demonstrate segment crossing if gap found", "Recommend rule tightening and micro-segmentation", "Provide test cases for ongoing validation"],
        REPORT,
    ),
    "cloud/aws": phases(
        SCOPE + ["Confirm AWS account IDs and regions in scope"],
        ["Enumerate IAM users, roles, policies with Pacu/ScoutSuite", "Check S3 bucket permissions and public access", "Review EC2 metadata IMDSv1 exposure", "Map Lambda, RDS, and secrets manager usage"],
        ["Exploit overly permissive IAM policies", "Access public or misconfigured S3 buckets", "Steal IAM creds from IMDS on compromised EC2", "Test privilege escalation paths in Pacu"],
        ["Demonstrate account or data compromise", "Document ARN and policy granting access", "Recommend least privilege and IMDSv2"],
        REPORT,
    ),
    "cloud/azure": phases(
        SCOPE + ["Obtain tenant ID and test credentials"],
        ["Run ROADtools and AzureHound for AAD enum", "Map subscriptions, resource groups, and RBAC", "Check storage account public access", "Review conditional access and MFA coverage"],
        ["Exploit privileged service principals", "Access storage blobs and key vaults", "Test cross-tenant sync and federation issues", "Validate PIM and admin role assignments"],
        ["Demonstrate subscription or tenant compromise path", "Document misconfigured role assignment", "Recommend Conditional Access and PIM"],
        REPORT,
    ),
    "cloud/gcp": phases(
        SCOPE + ["Identify GCP projects in scope"],
        ["Run gcp_scanner and Scout Suite", "Enumerate IAM bindings and service accounts", "Check GCS bucket IAM and public access", "Review compute default service account usage"],
        ["Exploit iam.serviceAccountUser chains", "Access open GCS buckets", "Steal metadata tokens from GCE instances", "Test org policy bypass"],
        ["Demonstrate project data access or priv esc", "Document binding and resource affected", "Recommend workload identity and bucket policies"],
        REPORT,
    ),
    "cloud/kubernetes": phases(
        SCOPE + ["Confirm cluster names and access level"],
        ["Run kube-hunter and kubectl auth can-i --list", "Enumerate pods, services, secrets, RBAC", "Check privileged pods and host mounts", "Review network policies and admission controllers"],
        ["Exploit weak RBAC (create pods, read secrets)", "Escape to node from privileged pod", "Access etcd or API server anonymously", "Test supply chain via malicious images"],
        ["Demonstrate cluster-admin or namespace compromise", "Document RoleBinding and exploited permission", "Recommend RBAC least privilege and Pod Security"],
        REPORT,
    ),
    "containers/docker": phases(
        SCOPE + ["Inventory container images and registries in scope"],
        ["Scan images with trivy and grype", "Run docker bench-security on hosts", "Check exposed Docker socket and API", "Review Dockerfile USER and capability drops"],
        ["Exploit CVE in container image", "Escape via mounted docker.sock", "Access secrets in env vars and layers", "Test registry authentication bypass"],
        ["Demonstrate host escape or secret theft", "Document image tag and CVE", "Recommend non-root users and socket protection"],
        REPORT,
    ),
    "containers/kubernetes-security": phases(
        SCOPE + ["Map namespaces and workloads in scope"],
        ["Run kubescape and Falco rule review", "Check Kyverno/Gatekeeper policy coverage", "Audit secrets mounted as env vars", "Review ingress and egress network policies"],
        ["Validate policy gaps with test deployments", "Trigger Falco alerts with benign attacks", "Test admission controller bypass", "Review RBAC for namespace admins"],
        ["Demonstrate policy violation impact", "Document missing control and MITRE mapping", "Recommend policy-as-code in CI"],
        REPORT,
    ),
    "containers/container-escape": phases(
        SCOPE + ["Gain shell in target container"],
        ["Run deepce and CDK auto-scan", "Check privileged mode, caps, host mounts", "Review seccomp/AppArmor profiles", "Identify kernel version for CVE escape"],
        ["Exploit cap_sys_admin, docker.sock, or kernel bug", "Validate host filesystem access", "Document cgroup and namespace breakout path", "Test only in authorized lab cluster"],
        ["Capture proof from host (not container) hostname", "Recommend gVisor/Kata and drop capabilities"],
        REPORT,
    ),
    "mobile/apk-ipa-analysis": phases(
        SCOPE + ["Obtain APK/IPA and package name in scope"],
        ["Decompile with jadx and apktool", "Search for hardcoded secrets and API keys", "Map exported activities and deep links", "Review network security config and pinning"],
        ["Validate secrets against live APIs", "Test backup and debug flags in manifest", "Run MobSF automated scan", "Identify certificate pinning implementation"],
        ["Demonstrate insecure data storage or API abuse", "Document file/line of vulnerable code", "Recommend secure storage and pinning"],
        REPORT,
    ),
    "mobile/frida": phases(
        SCOPE + ["Install app on rooted/jailbroken or patched test device"],
        ["Bypass root detection with Frida hooks", "Hook crypto and API call functions", "Intercept SSL with pinning bypass", "Log authentication tokens and parameters"],
        ["Modify runtime behavior (skip PIN, change values)", "Validate server-side controls still enforce auth", "Document hooked methods and offsets", "Use objection for rapid exploration"],
        ["Demonstrate client-only bypass with server impact proof", "Recommend server-side authorization"],
        REPORT,
    ),
    "mobile/ssl-pinning-bypass": phases(
        SCOPE + ["Configure Burp/mitm proxy on test device"],
        ["Identify pinning library (OkHttp, AFNetworking)", "Apply Frida ssl-kill-switch or objection", "Patch APK with apk-mitm if needed", "Verify HTTPS interception works"],
        ["Capture and modify API traffic", "Test sensitive endpoints via proxy", "Confirm pinning re-enabled in production builds", "Document bypass method per OS version"],
        ["Demonstrate API abuse via mitm on test build", "Recommend certificate transparency and pinning rotation"],
        REPORT,
    ),
    "mobile/deep-links": phases(
        SCOPE + ["Extract intent filters from manifest"],
        ["Map custom URL schemes and app links", "Fuzz path parameters and exported handlers", "Test WebView loading from deep link URLs", "Review authentication on linked screens"],
        ["Open sensitive screens without login via link", "Inject JavaScript via WebView deep link", "Validate intent hijacking between apps", "Test Android App Links verification bypass"],
        ["Demonstrate unauthorized screen access or XSS", "Document malicious link format"],
        REPORT,
    ),
    "binary/reverse-engineering": phases(
        SCOPE + ["Obtain binary and legal authorization to analyze"],
        ["Identify architecture, packing, and anti-debug", "Load in Ghidra/IDA and run auto-analysis", "Rename key functions and map call graph", "Extract strings, imports, and crypto constants"],
        ["Trace vulnerable function (strcpy, format string)", "Debug with gdb/gef to confirm flow", "Develop minimal PoC input", "Document offset and mitigation (ASLR, PIE, NX)"],
        ["Demonstrate controlled crash or exploit in lab", "Provide patched pseudocode recommendation"],
        REPORT,
    ),
    "binary/stack-overflow": phases(
        SCOPE + ["Run checksec on binary"],
        ["Find overflow in strcpy/gets/sprintf", "Calculate offset to return address", "Check NX, ASLR, canary, PIE", "Develop pattern with cyclic or pwntools"],
        ["Bypass canary if information leak exists", "Build ret2libc or ROP chain", "Validate exploit in gdb then standalone", "Test on target libc version"],
        ["Demonstrate EIP/RIP control and shell", "Document protections and bypass used", "Recommend safe functions and compiler flags"],
        REPORT,
    ),
    "binary/heap-exploitation": phases(
        SCOPE + ["Identify allocator (glibc dlmalloc, jemalloc)"],
        ["Trace malloc/free imbalance and UAF/double-free", "Layout heap with feng shui", "Leak libc address via unsorted bin", "Build exploit primitive (fastbin, tcache)"],
        ["Achieve arbitrary write or __malloc_hook overwrite", "Validate in gdb with heap visualization", "Test on exact libc version"],
        ["Demonstrate reliable shell in lab CTF binary", "Document heap layout and primitives"],
        REPORT,
    ),
}
