from methodologies._base import REPORT, SCOPE, phases

SPECIALIZED_METHODOLOGIES = {
    "blue-team/detection-engineering": phases(
        SCOPE + ["Define threat model and log sources available"],
        ["Research ATT&CK technique to detect", "Draft Sigma rule or SPL/KQL query", "Identify required log fields and parsers", "Peer review logic for false positive rate"],
        ["Test rule in dev SIEM with historical logs", "Run Atomic Red Team test to generate event", "Tune thresholds and exclusions", "Measure mean time to detect in simulation"],
        ["Deploy to production with alerting workflow", "Document detection data source and MITRE mapping", "Schedule quarterly rule review"],
        REPORT,
    ),
    "blue-team/siem-log-analysis": phases(
        SCOPE + ["Define incident hypothesis and time window"],
        ["Collect logs from relevant sources (AD, endpoint, proxy)", "Normalize timestamps to UTC", "Build timeline of key events", "Filter noise with known-good baselines"],
        ["Correlate IOCs across data sources", "Pivot on user, host, and IP entities", "Identify root cause and blast radius", "Validate findings with secondary source"],
        ["Document timeline for incident report", "Create detection queries for recurrence", "Recommend log retention and coverage gaps"],
        REPORT,
    ),
    "blue-team/threat-hunting": phases(
        SCOPE + ["Formulate hypothesis from intel or anomaly"],
        ["Select data source: EDR, SIEM, or Velociraptor", "Write hunt query for suspicious behavior", "Establish baseline of normal activity", "Run hunt across enterprise scope"],
        ["Investigate positive hits manually", "Determine true positive vs false positive", "Develop permanent detection from hunt", "Share IOCs and TTPs with team"],
        ["Document hunt results and new detections", "Update threat intel feed", "Schedule follow-up hunt"],
        REPORT,
    ),
    "blue-team/incident-response": phases(
        SCOPE + ["Activate IR plan and assign roles", "Preserve evidence and chain of custody"],
        ["Triage alert severity and scope", "Contain affected hosts and accounts", "Collect volatile and disk evidence", "Communicate with stakeholders per playbook"],
        ["Eradicate malware and attacker access", "Recover systems from clean backups", "Validate eradication with scans", "Monitor for re-compromise 30+ days"],
        ["Complete post-incident report", "Lessons learned and playbook updates", "Implement new detections from incident"],
        REPORT,
    ),
    "blue-team/malware-analysis": phases(
        SCOPE + ["Isolate analysis VM and disable network egress"],
        ["Calculate file hashes and check VT", "Static analysis: strings, imports, entropy", "Dynamic analysis in sandbox (Cuckoo)", "Debug with Ghidra/x64dbg for unpacking"],
        ["Extract C2 IOCs, mutexes, and persistence", "Develop YARA rule for family", "Document TTPs mapped to ATT&CK", "Share IOCs with SOC"],
        ["Recommend blocks and detection rules", "Securely archive sample with access controls"],
        REPORT,
    ),
    "cryptography/crypto-flaws": phases(
        SCOPE + ["Inventory crypto usage: TLS, at-rest, tokens, passwords"],
        ["Review algorithms and key lengths", "Test for hardcoded keys in source/binaries", "Analyze random number generation", "Check password hashing (bcrypt vs MD5)"],
        ["Exploit weak crypto to decrypt or forge", "Demonstrate token forgery with weak HMAC", "Validate TLS with testssl.sh", "Document deprecated algorithms in use"],
        ["Show plaintext recovery or signature bypass", "Recommend modern algorithms and key management"],
        REPORT,
    ),
    "cryptography/padding-oracle": phases(
        SCOPE + ["Identify CBC-mode encryption with error feedback"],
        ["Capture encrypted cookie or parameter", "Send modified ciphertext blocks", "Observe padding error vs valid responses", "Automate with padbuster or custom script"],
        ["Decrypt ciphertext byte-by-byte", "Forge valid ciphertext for chosen plaintext", "Validate on every encrypted field", "Test in lab before production"],
        ["Demonstrate account takeover via forged cookie", "Recommend AES-GCM or encrypt-then-MAC"],
        REPORT,
    ),
    "cryptography/tls-ssl": phases(
        SCOPE + ["List all TLS endpoints and versions required"],
        ["Run testssl.sh and sslyze scans", "Check certificate validity and chain", "Identify weak ciphers (RC4, 3DES, export)", "Test for Heartbleed, ROBOT, CRIME variants"],
        ["Attempt downgrade to TLS 1.0/1.1", "Validate HSTS and certificate pinning", "Document findings per endpoint", "Compare against Mozilla SSL config guide"],
        ["Demonstrate MITM in lab with weak config", "Provide cipher suite hardening steps"],
        REPORT,
    ),
    "devsecops/pipeline-security": phases(
        SCOPE + ["Map CI/CD pipeline stages and secrets usage"],
        ["Review GitHub Actions / GitLab CI YAML", "Check secret storage and fork PR exposure", "Audit pipeline permissions and tokens", "Scan dependencies with Snyk/Dependabot"],
        ["Attempt poisoned PR pipeline execution", "Test secret exfiltration from workflow", "Validate branch protection rules", "Review artifact signing and provenance"],
        ["Demonstrate supply chain attack path in fork", "Recommend OIDC, least privilege, and approval gates"],
        REPORT,
    ),
    "devsecops/iac-security": phases(
        SCOPE + ["Collect Terraform, CloudFormation, K8s manifests"],
        ["Run checkov, tfsec, and kics scans", "Review public security group rules", "Check IAM wildcards and admin policies", "Validate encryption flags on storage"],
        ["Exploit misconfiguration in test account", "Demonstrate open S3 or SG 0.0.0.0/0 impact", "Prioritize findings by exploitability", "Integrate scans into PR checks"],
        ["Report with line numbers and fix snippets", "Recommend policy-as-code guardrails"],
        REPORT,
    ),
    "devsecops/supply-chain": phases(
        SCOPE + ["Generate SBOM with syft for critical apps"],
        ["Scan dependencies for known CVEs", "Review typosquatting and maintainer risks", "Verify image signatures with cosign", "Audit private registry access controls"],
        ["Demonstrate dependency confusion in lab", "Test compromised package update path", "Validate provenance attestation", "Document third-party risk tiering"],
        ["Recommend SBOM in releases and signed artifacts"],
        REPORT,
    ),
    "forensics/disk-memory": phases(
        SCOPE + ["Secure legal authority and chain of custody forms"],
        ["Acquire disk image with FTK Imager/write-blocker", "Verify SHA-256 hash of image", "Run Volatility on memory dump", "Mount read-only for Autopsy analysis"],
        ["Extract timeline, browser history, and malware", "Recover deleted files and registry hives", "Correlate artifacts across users", "Document tool versions and methods"],
        ["Produce forensic report admissible to process", "Preserve original media securely"],
        REPORT,
    ),
    "forensics/network": phases(
        SCOPE + ["Define capture window and legal authorization"],
        ["Collect PCAP from tap or SPAN port", "Analyze with Wireshark and Zeek", "Reconstruct sessions and file extractions", "Identify C2 beaconing patterns"],
        ["Extract IOCs: IPs, domains, JA3, URIs", "Correlate with endpoint and DNS logs", "Build attack timeline from packets", "Document retention and privacy handling"],
        ["Deliver IOC package to SOC for blocking", "Archive PCAP with access controls"],
        REPORT,
    ),
    "forensics/cloud": phases(
        SCOPE + ["Identify cloud account and incident timeframe"],
        ["Pull CloudTrail / Azure Activity / GCP Audit logs", "Review IAM changes and API calls", "Correlate with GuardDuty/Sentinel alerts", "Preserve logs before retention expiry"],
        ["Reconstruct attacker API sequence", "Identify compromised credentials and resources", "Scope data access and exfiltration", "Document region and account affected"],
        ["Recommend credential rotation and policy fixes", "Enable additional logging if gaps found"],
        REPORT,
    ),
    "growth/cve-research": phases(
        SCOPE + ["Select target software and version range"],
        ["Monitor NVD, vendor advisories, and CISA KEV", "Set up vulnerable version in isolated VM", "Diff patches between fixed and vulnerable", "Fuzz or audit source for bug class"],
        ["Develop minimal crash or PoC", "Confirm exploitability and impact", "Write coordinated disclosure report", "Submit via vendor VDP or ZDI"],
        ["Publish writeup after patch and CVE assignment", "Add nuclei template for community"],
        REPORT,
    ),
    "growth/writeups": phases(
        SCOPE + ["Confirm disclosure timeline and program permission"],
        ["Reconstruct finding from notes and Burp history", "Write clear impact statement for readers", "Redact PII, keys, and out-of-scope details", "Add screenshots and HTTP transcripts"],
        ["Peer review for accuracy and reproducibility", "Publish on blog or HackerOne Hacktivity", "Engage with community feedback", "Link to CWE and remediation resources"],
        ["Update portfolio and LinkedIn respectfully", "Credit collaborators and original researchers"],
        REPORT,
    ),
    "iot/firmware-analysis": phases(
        SCOPE + ["Obtain firmware legally (download, dump, purchase)"],
        ["Extract with binwalk and identify filesystem", "Emulate with Firmadyne/QEMU if possible", "Analyze binaries in Ghidra", "Search for hardcoded creds and backdoors"],
        ["Test default telnet/SSH credentials", "Identify vulnerable services on ports", "Check unsigned update mechanism", "Review kernel and BusyBox versions"],
        ["Demonstrate device compromise in lab", "Report to vendor via coordinated disclosure"],
        REPORT,
    ),
    "iot/hardware-interfaces": phases(
        SCOPE + ["Document board and chip identifiers"],
        ["Identify UART pads with multimeter/continuity", "Connect Bus Pirate or USB-serial at correct baud", "Dump flash via SPI/JTAG if protected", "Capture boot sequence over serial"],
        ["Access root shell or firmware dump", "Document pinout and voltage levels", "Avoid damaging hardware with wrong voltage"],
        ["Analyze dumped firmware offline", "Recommend disable debug ports in production"],
        REPORT,
    ),
    "osint/people-org": phases(
        SCOPE + ["Define OSINT scope and privacy/legal boundaries"],
        ["Run theHarvester for emails and subdomains", "Use Maltego for relationship mapping", "Search LinkedIn and public records", "Collect breach data via HIBP (defensive use)"],
        ["Verify data accuracy across sources", "Build org chart and email format", "Identify key personnel for phishing sim (authorized)", "Document sources and collection dates"],
        ["Deliver intel report for red team or defense", "Do not harass or dox individuals"],
        REPORT,
    ),
    "osint/data-breach-search": phases(
        SCOPE + ["Confirm authorized defensive use only"],
        ["Query HIBP API for corporate domain emails", "Use authorized breach monitoring services", "Correlate exposed passwords with policy violations", "Never use data for unauthorized login attempts"],
        ["Notify affected users via security team", "Force password resets for exposed accounts", "Measure credential stuffing risk", "Document breach sources and dates"],
        ["Recommend MFA and password manager adoption", "Monitor for ongoing exposure"],
        REPORT,
    ),
    "social-engineering/phishing": phases(
        SCOPE + ["Obtain written phishing simulation authorization"],
        ["Define targets, timing, and forbidden pretexts", "Build realistic lure and landing page", "Configure gophish campaign and tracking", "Get legal/comms approval on email content"],
        ["Launch campaign within agreed window", "Track click and credential submission rates", "Stop campaign at agreed end time", "Prepare debrief without shaming individuals"],
        ["Deliver metrics to security awareness team", "Recommend training for clicked users", "Securely delete captured test credentials"],
        REPORT,
    ),
    "social-engineering/pretexting": phases(
        SCOPE + ["Define approved pretext scenarios and boundaries"],
        ["Research target org publicly for believable story", "Prepare callback numbers and personas", "Coordinate with client security contact", "Document stop phrases if target uncomfortable"],
        ["Execute phone or in-person pretext", "Attempt information elicitation only within ROE", "End immediately if target requests verification", "Log outcomes without recording illegally"],
        ["Debrief client with lessons learned", "Recommend verification procedures for staff"],
        REPORT,
    ),
    "reporting/vulnerability-reports": phases(
        SCOPE + ["Confirm program template and severity rubric"],
        ["Write executive summary (1–2 sentences)", "Detail reproduction steps numbered exactly", "Include HTTP requests, screenshots, and video", "State impact in business terms"],
        ["Assign CVSS or program severity with justification", "Suggest specific remediation steps", "Proofread for clarity and redact secrets", "Submit via platform and monitor triage"],
        ["Respond to analyst questions promptly", "Verify fix when marked resolved", "Request disclosure timeline if publishing"],
        REPORT,
    ),
    "secure-code-review/sast": phases(
        SCOPE + ["Define codebase scope and languages"],
        ["Run semgrep and CodeQL with security rulesets", "Triage findings by reachability and severity", "Manual review of auth, crypto, and injection hotspots", "Trace data flow from source to sink"],
        ["Confirm true positives with PoC or debugger", "Eliminate false positives with dev team", "Prioritize fixes by exploitability", "Integrate SAST into CI pipeline"],
        ["Deliver findings with file:line references", "Recommend secure coding guidelines per issue"],
        REPORT,
    ),
    "secure-code-review/threat-modeling": phases(
        SCOPE + ["Gather architecture docs and data classification"],
        ["Draw data flow diagram with trust boundaries", "Apply STRIDE to each component", "Rank threats by likelihood × impact", "Map mitigations to OWASP ASVS controls"],
        ["Create security test cases per threat", "Review with dev and product teams", "Store model in version control", "Schedule update on architecture changes"],
        ["Track mitigation tasks in Jira/Azure DevOps", "Verify mitigations in pen test or code review"],
        REPORT,
    ),
    "web3/smart-contracts": phases(
        SCOPE + ["Obtain contract address and scope on Immunefi/program"],
        ["Set up Foundry/Hardhat fork of mainnet state", "Run slither and mythril static analysis", "Review access control and upgrade patterns", "Map external calls and reentrancy surfaces"],
        ["Fuzz with Echidna/Foundry invariant tests", "Develop PoC exploit on local fork only", "Calculate funds at risk", "Never exploit mainnet without authorization"],
        ["Submit report with PoC and recommended fix", "Follow responsible disclosure timeline"],
        REPORT,
    ),
    "web3/wallet-dapp": phases(
        SCOPE + ["Identify dApp frontend and connected contracts"],
        ["Review wallet connect and transaction prompts", "Test for malicious approval requests", "Analyze JS for private key handling", "Simulate transactions on testnet/fork"],
        ["Demonstrate UI deception (wrong address, amount)", "Test phishing via cloned dApp domain", "Validate transaction simulation warnings", "Document user flow vulnerabilities"],
        ["Report UI/UX security issues to project", "Recommend clear signing prompts and domain verification"],
        REPORT,
    ),
    "automation/js-analysis": phases(
        SCOPE + ["Collect all JS bundles from in-scope apps"],
        ["Run linkfinder and secretfinder on bundles", "Crawl with katana for dynamic JS", "Map API routes and GraphQL endpoints", "Diff JS between releases for new surface"],
        ["Validate discovered endpoints are in scope", "Test endpoints for auth and injection", "Run nuclei on API paths found", "Archive JS versions for regression"],
        ["Feed findings into main testing workflow", "Automate weekly JS monitoring in CI"],
        REPORT,
    ),
    "automation/diffing": phases(
        SCOPE + ["Baseline previous release endpoints and responses"],
        ["Capture current sitemap and API schema", "Diff URLs, parameters, and response codes", "Flag new endpoints and removed auth", "Review changelog for security-relevant changes"],
        ["Prioritize new code paths for manual test", "Run automated scans only on delta", "Validate regressions on fixed bugs", "Update asset inventory automatically"],
        ["Report new attack surface to team", "Integrate diff into release pipeline"],
        REPORT,
    ),
    "automation/scope-tooling": phases(
        SCOPE + ["Configure bbscope with platform API tokens"],
        ["Export in-scope domains and wildcards", "Normalize scope rules to regex/glob", "Deduplicate overlapping program scopes", "Validate out-of-scope exclusions"],
        ["Feed scope into recon automation scripts", "Alert on scope changes via scheduled pull", "Share scope file with team via git", "Document scope version per engagement"],
        ["Prevent testing out-of-scope assets", "Update Burp scope automatically"],
        REPORT,
    ),
}
