from methodologies._base import REPORT, SCOPE, phases

WEB_METHODOLOGIES = {
    "web/sqli": phases(
        SCOPE + ["Inventory all parameters, headers, and JSON fields hitting the database"],
        [
            "Map every endpoint that queries a database (forms, APIs, search, filters)",
            "Inject probe characters: `'`, `\"`, `)`, `;` and observe errors or diffs",
            "Test GET, POST, JSON body, cookies, and custom headers",
            "Identify ORM vs raw SQL usage via error messages or stack traces",
        ],
        [
            "Confirm with boolean pairs: `' AND 1=1--` vs `' AND 1=2--`",
            "Determine injection type: error, union, boolean blind, time blind, stacked",
            "For UNION: find column count via `ORDER BY n` or `UNION SELECT NULL,...`",
            "Validate time-based with `SLEEP(5)` / `WAITFOR DELAY` and measure response",
        ],
        [
            "Extract minimal proof: one row, table name, or auth bypass",
            "Avoid dumping full databases unless explicitly authorized",
            "Test write primitives (`INTO OUTFILE`, stacked queries) only in lab",
            "Chain to RCE only when in scope and with written approval",
        ],
        REPORT + ["Note database type, injection context, and parameterized query fix"],
    ),
    "web/xss": phases(
        SCOPE + ["Identify all user input reflection and storage points"],
        [
            "Map reflected, stored, and DOM-based XSS surfaces",
            "Review JavaScript sinks: `innerHTML`, `eval`, `document.write`, template literals",
            "Check CSP headers and nonce usage",
            "Enumerate contexts: HTML, attribute, JS string, URL, CSS",
        ],
        [
            "Inject canonical probes: `<script>alert(1)</script>`, `\"><img src=x onerror=alert(1)>`",
            "Bypass filters with encoding, tag mutation, and event handlers",
            "Test stored XSS by submitting payloads other users will trigger",
            "Validate DOM XSS via URL fragments and `postMessage` handlers",
        ],
        [
            "Demonstrate impact: cookie access, keylogged actions, or CSRF via XSS",
            "Use `alert(document.domain)` or benign `fetch` to prove execution",
            "Test session hijacking only with your own test accounts",
            "Document browser and context (Chrome/Firefox, logged-in role)",
        ],
        REPORT + ["Specify XSS type, sink, and output encoding fix"],
    ),
    "web/ssrf": phases(
        SCOPE + ["List all server-side URL fetch features (webhooks, importers, previews)"],
        [
            "Find parameters accepting URLs: `url=`, `path=`, `webhook`, `avatar`, `import`",
            "Review PDF generators, image processors, and link preview features",
            "Check cloud metadata endpoints as internal targets",
            "Map allowed protocols: http, https, file, gopher, dict",
        ],
        [
            "Point URL to Burp Collaborator / interactsh and confirm callback",
            "Test internal IPs: `127.0.0.1`, `169.254.169.254`, `10.0.0.0/8`",
            "Bypass filters with DNS rebinding, decimal IP, IPv6, or redirects",
            "Validate blind SSRF via timing and OOB DNS/HTTP",
        ],
        [
            "Read cloud metadata credentials (if in scope)",
            "Access internal admin panels or Redis/Elasticsearch",
            "Demonstrate port scan of internal network via response timing",
            "Stop at proof — avoid destructive internal actions",
        ],
        REPORT + ["Include bypass technique and network segmentation recommendation"],
    ),
    "web/idor": phases(
        SCOPE + ["Create two test accounts: attacker (low priv) and victim (target data)"],
        [
            "Collect object IDs from URLs, JSON bodies, and API responses",
            "Note predictable patterns: sequential ints, UUIDs, base64 blobs",
            "Map CRUD operations per resource type (orders, invoices, messages)",
            "Identify horizontal vs vertical privilege targets",
        ],
        [
            "Swap IDs in requests while keeping attacker's session token",
            "Test UUIDs — guessable or leaked from other endpoints?",
            "Replay requests with `X-User-Id` or `accountId` body fields changed",
            "Verify server enforces ownership on every method (GET/PUT/DELETE)",
        ],
        [
            "Access one victim record as minimal proof",
            "Test mass assignment: can attacker modify `role` or `userId`?",
            "Check batch/export endpoints for bulk IDOR",
            "Document API vs web UI authorization gaps",
        ],
        REPORT + ["Show exact ID swap and recommend server-side authorization checks"],
    ),
    "web/ssti": phases(
        SCOPE + ["Identify template engine from errors, headers, or tech stack"],
        [
            "Find template injection points: emails, reports, error pages, previews",
            "Probe with `{{7*7}}`, `${7*7}`, `<%= 7*7 %>`, `#{7*7}`",
            "Note which syntax evaluates to `49` in response",
            "Review user-controlled template fragments in admin features",
        ],
        [
            "Confirm engine: Jinja2, Twig, Freemarker, Velocity, Smarty, etc.",
            "Escalate to info disclosure payloads per engine cheat sheet",
            "Test sandbox escapes documented for that engine version",
            "Validate blind SSTI via time delays or OOB callbacks",
        ],
        [
            "Demonstrate file read or limited RCE with engine-specific payload",
            "Use tplmap for automated exploitation in lab environments",
            "Avoid production RCE unless explicitly authorized",
            "Capture template context that enabled injection",
        ],
        REPORT + ["Name template engine and recommend logic-less templates or sandboxing"],
    ),
    "web/lfi-rfi": phases(
        SCOPE + ["Find file inclusion parameters: `file=`, `page=`, `template=`, `lang=`"],
        [
            "Enumerate path traversal: `../../../etc/passwd`, `....//....//etc/passwd`",
            "Test PHP wrappers: `php://filter/convert.base64-encode/resource=index`",
            "Check for RFI by pointing to attacker-hosted file",
            "Identify OS from path syntax and error messages",
        ],
        [
            "Confirm local file read with known files (`/etc/passwd`, `win.ini`)",
            "Bypass filters: null byte (legacy), encoding, double traversal",
            "Read source code via wrapper filters",
            "Validate RFI only in controlled lab with your server",
        ],
        [
            "Chain LFI to RCE via log poisoning or `/proc/self/environ`",
            "Demonstrate minimal file read as proof",
            "Document exact parameter and traversal depth",
            "Test upload + include chains if applicable",
        ],
        REPORT + ["Recommend allow-list file paths and disable remote includes"],
    ),
    "web/xxe": phases(
        SCOPE + ["Locate XML parsers: SOAP, SAML, RSS, Office uploads, SVG"],
        [
            "Identify endpoints accepting `application/xml` or file uploads",
            "Test basic external entity: `<!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]>`",
            "Check JSON endpoints that accept `__proto__` or XML content types",
            "Review document import and data interchange features",
        ],
        [
            "Confirm file read or SSRF via entity expansion",
            "Test blind XXE with OOB DTD on collaborator server",
            "Try parameter entities and error-based exfiltration",
            "Validate billion-laughs DoS only in isolated lab",
        ],
        [
            "Extract one file or internal HTTP request as proof",
            "Demonstrate SSRF to metadata service if cloud-hosted",
            "Avoid disruptive DoS payloads on production",
            "Document parser library and version",
        ],
        REPORT + ["Disable external entities and use defused XML parsers"],
    ),
    "web/deserialization": phases(
        SCOPE + ["Identify serialization format: Java, PHP, .NET, Python pickle, Ruby"],
        [
            "Find cookies, hidden fields, or API bodies with encoded blobs",
            "Decode base64 and inspect magic bytes or format markers",
            "Search source/repos for `ObjectInputStream`, `unserialize`, `BinaryFormatter`",
            "Map gadget chains available for detected libraries",
        ],
        [
            "Replace serialized object with known gadget payload (ysoserial/phpggc)",
            "Confirm behavior change or callback from malicious object",
            "Test type confusion and signing bypass on tokens",
            "Validate in isolated JVM/PHP version matching target",
        ],
        [
            "Achieve RCE or auth bypass with minimal gadget chain",
            "Document library versions enabling the chain",
            "Do not deploy persistent backdoors",
            "Capture generated payload and server response",
        ],
        REPORT + ["Recommend avoiding native deserialization of untrusted data"],
    ),
    "web/race-condition": phases(
        SCOPE + ["Identify limit-once operations: transfers, votes, coupon redemption"],
        [
            "Map state-changing endpoints with concurrency impact",
            "Review single-use tokens, inventory counters, rate limits",
            "Note microservice timing windows between check and use",
            "Identify financial or privilege-escalation targets",
        ],
        [
            "Send 20–100 parallel requests with Burp Turbo Intruder or asyncio",
            "Compare single request vs burst outcomes",
            "Measure window: add delays between check and update if possible",
            "Test last-byte sync and HTTP/2 single-connection races",
        ],
        [
            "Demonstrate double spend, double vote, or limit bypass",
            "Capture timing diagram and success rate",
            "Prove business impact with account balances or quotas",
            "Stop after clear proof — avoid harming other users",
        ],
        REPORT + ["Recommend database transactions, locks, or idempotency keys"],
    ),
    "web/open-redirect": phases(
        SCOPE + ["Find redirect parameters: `url`, `next`, `return`, `redirect`, `continue`"],
        [
            "Crawl application for 302/301 with user-controlled Location",
            "Check OAuth `redirect_uri` and logout redirects",
            "Test path-only vs full URL validation",
            "Review JavaScript `window.location` assignments from URL params",
        ],
        [
            "Inject external domain and confirm redirect follows",
            "Bypass filters: `//evil.com`, `\\/evil.com`, `@evil.com`, encoding",
            "Test open redirect chained to OAuth token theft",
            "Validate stored vs reflected redirect variants",
        ],
        [
            "Show phishing scenario with realistic redirect chain",
            "Demonstrate token leakage via redirect if applicable",
            "Use benign destination domain you control",
            "Document every bypass variant that worked",
        ],
        REPORT + ["Recommend allow-list redirect destinations"],
    ),
    "web/prototype-pollution": phases(
        SCOPE + ["Identify JS merge/extend on user JSON (`__proto__`, `constructor.prototype`)"],
        [
            "Map client-side libraries: lodash merge, jQuery.extend, recursive assign",
            "Find server-side Node merge on JSON bodies",
            "Review query string parsers that build nested objects",
            "Check GraphQL variable merging and template configs",
        ],
        [
            "Send `{\"__proto__\": {\"isAdmin\": true}}` and observe auth changes",
            "Test `constructor.prototype` pollution variants",
            "Use ppmap or manual JSON nesting for discovery",
            "Validate server-side pollution via response or behavior",
        ],
        [
            "Demonstrate auth bypass or RCE gadget if available",
            "Show client-side XSS via polluted config sinks",
            "Document polluted property and affected code path",
            "Test fix by freezing Object.prototype in lab",
        ],
        REPORT + ["Recommend `Object.create(null)` maps and safe merge libraries"],
    ),
    "web/cors": phases(
        SCOPE + ["Inventory APIs returning `Access-Control-Allow-*` headers"],
        [
            "Send cross-origin requests from attacker origin with credentials",
            "Test `Origin: null` and subdomain variations",
            "Check preflight for sensitive methods (PUT, DELETE)",
            "Map endpoints returning PII with permissive CORS",
        ],
        [
            "Confirm `Access-Control-Allow-Origin: *` with credentials (invalid but misconfigured)",
            "Test reflected Origin without validation",
            "Build HTML PoC that exfiltrates JSON to attacker server",
            "Validate null origin and regex bypasses",
        ],
        [
            "Demonstrate reading authenticated API data cross-origin",
            "Show impact with realistic attacker page PoC",
            "Test write operations if CORS allows dangerous methods",
            "Use test accounts only",
        ],
        REPORT + ["Recommend strict Origin allow-list and avoid credentialed wildcard CORS"],
    ),
    "web/clickjacking": phases(
        SCOPE + ["Check `X-Frame-Options` and `Content-Security-Policy frame-ancestors`"],
        [
            "Identify sensitive actions: transfer, delete, change email, grant admin",
            "Test if pages load in iframe on attacker domain",
            "Review frame-busting JS (often bypassable)",
            "Map double-click and drag-drop UI actions",
        ],
        [
            "Build HTML PoC overlaying invisible iframe",
            "Test mobile viewport and touch event hijacking",
            "Validate bypass of `X-Frame-Options: SAMEORIGIN` via subdomain",
            "Check CSP `frame-ancestors` coverage on all sensitive routes",
        ],
        [
            "Record video of victim click performing protected action",
            "Demonstrate with self-click on PoC page",
            "Show combined impact with CSRF if cookies not protected",
            "Do not target real users",
        ],
        REPORT + ["Recommend `frame-ancestors 'none'` or explicit allow-list"],
    ),
    "web/http-request-smuggling": phases(
        SCOPE + ["Confirm front-end/back-end server pair (CDN + origin, load balancer)"],
        [
            "Identify CL.TE and TE.CL desync opportunities with Burp smuggler",
            "Test HTTP/2 downgrading to H1 smuggling vectors",
            "Map timeout and buffer differences between servers",
            "Review reverse proxy documentation for known issues",
        ],
        [
            "Send ambiguous `Content-Length` vs `Transfer-Encoding` requests",
            "Observe desync via response queue poisoning indicators",
            "Validate with timing and response-order anomalies",
            "Test h2c smuggling if HTTP/2 front-end present",
        ],
        [
            "Demonstrate request hijacking or cache poisoning via smuggle",
            "Capture second request affecting other users (in lab)",
            "Document exact server versions and header combinations",
            "Avoid sustained poisoning on production",
        ],
        REPORT + ["Recommend single consistent HTTP parser and disable TE upgrades"],
    ),
    "web/web-cache-poisoning": phases(
        SCOPE + ["Identify CDN/cache in front of dynamic content"],
        [
            "Find unkeyed headers and parameters with Param Miner",
            "Test `X-Forwarded-Host`, `X-Original-URL`, custom headers",
            "Map cacheable responses containing user input reflection",
            "Review cache key configuration if accessible",
        ],
        [
            "Inject reflected XSS or redirect via unkeyed input",
            "Confirm poisoned response served to other users",
            "Test fat GET, parameter cloaking, and key normalization",
            "Validate with cache buster param for victim simulation",
        ],
        [
            "Demonstrate stored poison affecting multiple clients",
            "Show XSS or open redirect served from cache",
            "Document cache TTL and purge behavior",
            "Purge poison after test if possible",
        ],
        REPORT + ["Include unkeyed inputs in cache key or disable caching on dynamic routes"],
    ),
    "web/business-logic": phases(
        SCOPE + ["Map complete user workflows: checkout, signup, subscription, rewards"],
        [
            "Diagram state machine for each multi-step process",
            "Identify price, quantity, and role fields in requests",
            "Review negative numbers, zero amounts, and integer overflow",
            "Find race windows between validation and commit",
        ],
        [
            "Skip steps by calling final API directly",
            "Modify prices, discounts, and currencies client-side",
            "Replay coupons, referral bonuses, and loyalty points",
            "Test role escalation via workflow reorder",
        ],
        [
            "Complete purchase at $0 or negative total as proof",
            "Demonstrate unauthorized feature access",
            "Show impact with finance or fraud team context",
            "Use test payment gateways only",
        ],
        REPORT + ["Recommend server-side price authority and workflow tokens"],
    ),
    "web/crlf-injection": phases(
        SCOPE + ["Find parameters reflected in HTTP response headers"],
        [
            "Inject `%0d%0a` into redirects, cookies, and custom headers",
            "Test log injection via User-Agent and Referer",
            "Map Set-Cookie injection points",
            "Review email/header generation from user input",
        ],
        [
            "Confirm new header injection: `%0d%0aSet-Cookie: injected=true`",
            "Test response splitting leading to XSS",
            "Validate cache poisoning via injected headers",
            "Use crlfuzz for automated discovery",
        ],
        [
            "Demonstrate XSS via split response body",
            "Show session fixation via injected cookies",
            "Document encoding bypasses that worked",
            "Avoid log flooding on production",
        ],
        REPORT + ["Strip CR/LF from header values and encode outputs"],
    ),
    "web/command-injection": phases(
        SCOPE + ["Locate OS command invocation: ping, nslookup, image tools, backups"],
        [
            "Identify parameters passed to shell: IP, hostname, filename",
            "Test separators: `;`, `|`, `&&`, `||`, `` ` ``, `$()`",
            "Review blind command injection via time delays",
            "Map outbound network for OOB exfiltration",
        ],
        [
            "Confirm with `; sleep 5` or `| whoami` output in response",
            "Use commix for automated detection",
            "Test argument injection vs full command injection",
            "Validate Windows vs Linux payload sets",
        ],
        [
            "Demonstrate file read or reverse shell in lab only",
            "Capture command output in HTTP response as proof",
            "Avoid destructive commands on production",
            "Document sanitization bypass used",
        ],
        REPORT + ["Recommend exec APIs without shell and strict input allow-lists"],
    ),
    "web/nosql-injection": phases(
        SCOPE + ["Identify MongoDB/CouchDB queries built from JSON input"],
        [
            "Map login and search endpoints accepting JSON bodies",
            "Test operator injection: `{\"$ne\": null}`, `{\"$gt\": \"\"}`",
            "Review JavaScript injection in `$where` clauses",
            "Check API vs web login differences",
        ],
        [
            "Bypass auth with `{\"username\": {\"$ne\": null}, \"password\": {\"$ne\": null}}`",
            "Extract data via boolean blind NoSQL techniques",
            "Use nosqlmap for automated tests",
            "Validate error messages leaking query structure",
        ],
        [
            "Login as admin or read one document as proof",
            "Demonstrate data exfiltration path",
            "Document database type and vulnerable parameter",
            "Avoid dumping entire collections",
        ],
        REPORT + ["Use typed queries and disable `$where` / server-side JS"],
    ),
    "web/http-parameter-pollution": phases(
        SCOPE + ["Note frameworks that merge duplicate parameters differently"],
        [
            "Send duplicate keys: `id=1&id=2` in query and body",
            "Test mixed GET/POST parameter precedence",
            "Review WAF bypass via parameter splitting",
            "Map front-end vs back-end parameter selection",
        ],
        [
            "Confirm auth bypass when front-end checks first value, back-end uses last",
            "Test HPP in OAuth and SAML flows",
            "Validate file upload boundary HPP",
            "Compare behavior across server stacks",
        ],
        [
            "Demonstrate privilege or filter bypass",
            "Chain HPP with other vulnerabilities",
            "Document server-specific behavior",
            "Capture raw HTTP showing duplicate keys",
        ],
        REPORT + ["Normalize parameter handling server-side"],
    ),
    "web/websockets": phases(
        SCOPE + ["Capture WebSocket handshake and message format in Burp"],
        [
            "Map subscribe/send message types and channels",
            "Test missing Origin validation on handshake",
            "Review auth token placement: cookie vs message",
            "Identify sensitive broadcast channels",
        ],
        [
            "Connect from unauthorized Origin header",
            "Subscribe to other users' rooms without permission",
            "Inject SQL/commands in message handlers",
            "Fuzz message JSON fields for injection",
        ],
        [
            "Receive another user's messages or send as victim",
            "Demonstrate XSS via WebSocket-reflected content",
            "Document message schema and auth gap",
            "Use two test sessions for proof",
        ],
        REPORT + ["Validate Origin, authenticate per message, authorize channels"],
    ),
    "web/information-disclosure": phases(
        SCOPE + ["Define sensitive data types: PII, keys, internal paths, stack traces"],
        [
            "Crawl for `.git`, `.env`, backup files, and directory listings",
            "Run nuclei exposures templates and trufflehog on repos",
            "Review JS bundles for API keys and internal URLs",
            "Check error pages, debug flags, and `/actuator` endpoints",
        ],
        [
            "Confirm downloadable `.git` or exposed `.env`",
            "Validate API keys found in JS are active",
            "Test verbose errors on malformed input",
            "Scan responses for SSN, tokens, and internal IPs",
        ],
        [
            "Demonstrate account takeover via leaked key if applicable",
            "Show internal network map from disclosure",
            "Redact secrets in report — prove type not full value",
            "Notify program immediately for critical leaks",
        ],
        REPORT + ["Remove debug endpoints and rotate exposed credentials"],
    ),
    "web/ldap-xpath-injection": phases(
        SCOPE + ["Identify LDAP/XPath login and search features"],
        [
            "Map LDAP filters built from username fields",
            "Test wildcards: `*)(uid=*))(|(uid=*`",
            "Probe XPath in XML search and config APIs",
            "Review error messages for directory structure",
        ],
        [
            "Bypass LDAP auth with injection payloads",
            "Extract attributes via blind LDAP techniques",
            "Validate XPath boolean injection on XML queries",
            "Test encoded and double-encoded variants",
        ],
        [
            "Login without valid password as proof",
            "Enumerate users or roles minimally",
            "Document directory type (AD/OpenLDAP)",
            "Avoid bulk directory dumps",
        ],
        REPORT + ["Use parameterized LDAP filters and bind authentication"],
    ),
    "web/dom-clobbering": phases(
        SCOPE + ["Review pages using named DOM elements and inline config scripts"],
        [
            "Find `window.config`, `defaultAvatar`, and similar globals",
            "Identify scripts reading `document.getElementById` named anchors",
            "Map gadget paths in third-party libraries",
            "Check HTML sanitizers allowing `id`/`name` attributes",
        ],
        [
            "Inject `<a id=config href=evil>` clobbering globals",
            "Test CSP bypass via clobbered script loaders",
            "Validate XSS or data leak via clobbered URL",
            "Review DOMPurify config for known bypasses",
        ],
        [
            "Demonstrate script load from attacker domain via clobber",
            "Show impact on authenticated pages",
            "Document clobbered identifier and consuming script",
            "Pair with stored HTML injection if needed",
        ],
        REPORT + ["Avoid named element lookups; use `data-*` attributes safely"],
    ),
}
