from tips._base import t

INFRA_TIPS = {
    "network/active-directory": [
        t("BloodHound first", "Run SharpHound before manual enum — paths to DA save hours of guessing."),
        t("Low-priv is enough", "Domain user creds unlock Kerberoast, ACL abuse, and LLMNR poisoning."),
        t("Tier 0 focus", "Document paths to Domain Admins, not every local admin on workstations."),
        t("Snapshot before DCSync", "Credential dumps are destructive evidence — get written approval.", "warning"),
        t("Clean up artifacts", "Remove created SPNs, accounts, and scheduled tasks before engagement ends."),
    ],
    "network/active-directory/kerberoasting": [
        t("Target high-value SPNs", "SQL, backup, and legacy service accounts often have weak passwords."),
        t("RC4 tickets crack faster", "Request RC4 enctype when possible — AES tickets are slower to crack."),
        t("Rubeus automation", "`Rubeus.exe kerberoast /outfile:hashes.txt` from any domain user session."),
        t("Don't spray cracked creds", "Validate one account, then report — password spraying risks lockouts.", "warning"),
        t("Recommend gMSA", "Group Managed Service Accounts eliminate roastable static passwords."),
    ],
    "network/bloodhound": [
        t("All collection methods", "Run `-c All` once, then targeted collections on schedule."),
        t("CE vs legacy", "BloodHound CE uses different ingest — match collector to your version."),
        t("Shortest path export", "Screenshot the path graph for reports — analysts love visual proof."),
        t("Validate top 3 paths", "BloodHound suggests many paths — manually confirm the shortest real one."),
        t("Defensive Cypher", "Export remediation queries (`MATCH ...`) for blue team handoff."),
    ],
    "network/dcsync": [
        t("Rights check first", "BloodHound shows who can DCSync — don't guess replication ACLs."),
        t("Single account dump", "Start with `secretsdump -just-dc-user krbtgt` before full domain export."),
        t("Golden ticket path", "krbtgt hash enables Golden Ticket — document impact clearly."),
        t("Protected Users", "DA in Protected Users blocks NTLM — plan auth method accordingly."),
        t("Secure hash handling", "Encrypt dumps at rest and delete after test.", "warning"),
    ],
    "network/pentesting": [
        t("Rules of engagement", "Define stop conditions, excluded hosts, and emergency contact before scanning."),
        t("External then internal", "Map internet-facing attack surface before assuming VPN access."),
        t("Default creds checklist", "Tomcat/manager, Jenkins, Grafana, vCenter — test on every service."),
        t("Segmentation proof", "Show which zone crossing matters — not just individual CVEs."),
        t("Journal everything", "Timestamp each shell, cred, and host for clean reporting."),
    ],
    "network/privilege-escalation/windows": [
        t("winPEAS first pass", "Automated output highlights SeImpersonate, unquoted paths, and AlwaysInstallElevated."),
        t("Potato family", "SeImpersonatePrivilege → PrintSpoofer or GodPotato on modern builds."),
        t("Service permissions", "`accesschk.exe -uwcqv *` on services — weak DACLs are common."),
        t("Saved creds hunt", "`cmdkey /list` and registry blobs under `HKLM\\SECURITY`."),
        t("Patch gap = quick win", "Watson/CVE mapping on stale servers finds kernel exploits fast."),
    ],
    "network/privilege-escalation/linux": [
        t("sudo -l before exploits", "`sudo -l` output often gives direct root without kernel bugs."),
        t("SUID GTFOBins", "Match SUID binaries to gtfobins.github.io one-liners."),
        t("Capabilities", "`getcap -r / 2>/dev/null` — cap_setuid on python = instant root."),
        t("Cron writable scripts", "World-writable cron entries running as root are still everywhere."),
        t("Container on host?", "Docker group membership equals root — check `id` and socket access."),
    ],
    "network/lateral-movement": [
        t("CrackMapExec swiss army", "`crackmapexec smb targets.txt -u user -p pass --shares` maps the network."),
        t("Pass-the-hash hygiene", "Use `-H NTLM` only on in-scope hosts — avoid domain-wide spraying."),
        t("WinRM over SMB", "evil-winrm when 5985 open — often less monitored than psexec."),
        t("Document the path", "Each hop: source host, cred used, target, timestamp."),
        t("Stop at objective", "Don't wander into out-of-scope VLANs after proving segment access."),
    ],
    "network/wireless": [
        t("Passive recon first", "Identify clients and hidden SSIDs before transmitting deauth frames."),
        t("PMKID capture", "`hcxdumptool` can grab PMKID without full handshake on WPA2."),
        t("Enterprise cert check", "Test if clients accept any RADIUS cert — evil twin on WPA-Enterprise."),
        t("Client isolation", "Associated to guest WiFi? Probe for lateral access to corporate VLAN."),
        t("Legal and location", "Wireless tests need physical authorization at the site.", "warning"),
    ],
    "network/firewall-segmentation": [
        t("Diagram vs reality", "Probe every zone boundary — policies drift from documentation."),
        t("Dual-homed hosts", "Jump boxes and backup servers often bridge segments unintentionally."),
        t("Management plane", "iLO, IPMI, and hypervisor APIs frequently sit on flat networks."),
        t("hping3 for ACL map", "Send SYN to one port at a time across zones to build allow matrix."),
        t("Business justification", "Report each unexpected flow with risk — not just open port lists."),
    ],
    "cloud/aws": [
        t("Pacu quick start", "`pacu` modules for IAM privesc after any cred leak."),
        t("IMDSv1 check", "Curl `169.254.169.254` without token — IMDSv1 on EC2 is cred theft."),
        t("S3 bucket names", "Guess `company-backup`, `company-dev` — many are public or listable."),
        t("Role chaining", "Look for `sts:AssumeRole` chains from low-priv to admin."),
        t("Region sweep", "Clients forget ap-southeast-1 — enumerate all regions for resources."),
    ],
    "cloud/azure": [
        t("ROADtools enum", "`roadrecon auth` then `roadrecon gather` maps entire AAD tenant."),
        t("Storage public blobs", "`az storage blob list` with anonymous auth on guessed accounts."),
        t("PIM gaps", "Permanent Global Admin assignments bypass PIM — hunt in AzureHound."),
        t("Service principal secrets", "Expired secrets in repos — search GitHub for `client_secret`."),
        t("Conditional Access", "Note MFA gaps on legacy auth protocols in report."),
    ],
    "cloud/gcp": [
        t("gcloud auth list", "Stolen `application_default_credentials.json` unlocks project APIs."),
        t("GCS IAM fuzz", "`gsutil iam get gs://bucket` on naming-convention buckets."),
        t("Default SA on GCE", "Compute default SA often has editor — metadata token is the key."),
        t("Org policy bypass", "Test cross-project SA impersonation when folder policies look strict."),
        t("gcp_scanner", "Run on every project ID found in DNS or JS bundles."),
    ],
    "cloud/kubernetes": [
        t("kubectl auth can-i", "`kubectl auth can-i --list` shows effective permissions immediately."),
        t("Secrets in etcd", "Anonymous API or etcd access = all cluster secrets."),
        t("Privileged pod escape", "Pods with `privileged: true` and host mounts — test kubelet escape."),
        t("kube-hunter remote", "Run against API server URL from outside when port 6443 exposed."),
        t("Default namespace", "Dev clusters leave cluster-admin bindings in `default` — check RoleBindings."),
    ],
    "containers/docker": [
        t("Socket exposure", "`-v /var/run/docker.sock` in compose files = host root."),
        t("trivy in CI", "Scan images before runtime — CVEs in base images are common."),
        t("Secrets in layers", "`docker history` and dive reveal env vars baked into images."),
        t("CAP_SYS_ADMIN", "Capabilities not dropped? Container escape primitives multiply."),
        t("Registry auth", "Anonymous pull from private registry leaks proprietary images."),
    ],
    "containers/kubernetes-security": [
        t("kubescape NSA framework", "Baseline scan against NSA/CISA hardening guide."),
        t("Falco noise tuning", "Trigger benign violations first — tune before production alerts."),
        t("NetworkPolicy gaps", "Default allow egress — test DNS tunnel and metadata access."),
        t("Admission bypass", "Deploy test pod with forbidden securityContext — policy only matters if enforced."),
        t("Secrets as env vars", "Env vars appear in process list and crash dumps — prefer volume mounts."),
    ],
    "containers/container-escape": [
        t("deepce checklist", "Run deepce inside container — scores escape vectors automatically."),
        t("CAP_SYS_ADMIN + mount", "Mount host filesystem when cgroup devices allow it."),
        t("Kernel match matters", "Escape CVEs are kernel-specific — match exact host kernel."),
        t("Lab clusters only", "Never test escape primitives on production orchestrators.", "warning"),
        t("Proof from host", "Screenshot `hostname` from host namespace — not container ID."),
    ],
    "mobile/apk-ipa-analysis": [
        t("jadx + grep secrets", "`jadx -d out app.apk` then search for `api_key`, `password`, `Bearer`."),
        t("Exported components", "AndroidManifest exported activities/intents — test without login."),
        t("MobSF report", "Automated scan catches backup flags, weak crypto, and hardcoded keys."),
        t("Network security config", "Pinning declared but disabled in debug manifest variants."),
        t("Compare release vs debug", "Debug builds often disable pinning and enable logging."),
    ],
    "mobile/frida": [
        t("objection rapid recon", "`objection -g com.app explore` — ssl, root, and dump in minutes."),
        t("Hook crypto early", "Intercept `javax.crypto` or CommonCrypto before app init completes."),
        t("Spawn vs attach", "`frida -U -f com.app` bypasses some anti-debug on startup."),
        t("Document offsets", "iOS hooks need class/method names — Android needs full JNI signatures."),
        t("Server still rules", "Client bypass without server impact is usually informational."),
    ],
    "mobile/ssl-pinning-bypass": [
        t("Universal SSL kill", "frida-multiple-unpinning script covers OkHttp, AFNetworking, Flutter."),
        t("apk-mitm patch", "When Frida blocked, repackage APK with mitm proxy cert."),
        t("iOS trust store", "Install Burp CA on device and enable full trust in Settings."),
        t("Certificate transparency", "Some apps pin plus CT — note bypass method per OS version."),
        t("Production builds", "Confirm pinning enabled in release — debug-only pinning is not a vuln."),
    ],
    "mobile/deep-links": [
        t("adb intent fuzzing", "`adb shell am start -a android.intent.action.VIEW -d 'scheme://path'`"),
        t("WebView loading", "Deep link params reflected in WebView URL — test XSS and file access."),
        t("iOS universal links", "AASA file mistakes allow cross-app hijacking."),
        t("Auth on destination", "Open `/account/settings` via link without session cookie."),
        t("Intent filter export", "Exported handlers without permission = other apps can trigger them."),
    ],
    "binary/reverse-engineering": [
        t("strings before Ghidra", "Quick `strings -a binary` finds URLs, keys, and format strings."),
        t("checksec baseline", "NX, PIE, RELRO, canary — know protections before exploit dev."),
        t("Rename as you go", "Ghidra/IDA renaming saves hours on return visits."),
        t("Anti-debug bypass", "Patch `ptrace` checks or use `LD_PRELOAD` in lab only."),
        t("Version pin libraries", "Exploit gadgets depend on exact libc — record `ldd` output."),
    ],
    "binary/stack-overflow": [
        t("cyclic pattern", "pwntools `cyclic` finds exact offset faster than manual counting."),
        t("checksec first", "NX on? Plan ROP. Canary on? Need leak. PIE on? Need libc leak."),
        t("gdb gef/peda", "Visualize stack layout and canary position during development."),
        t("one_gadget last resort", "When ROP chain long, try one_gadget on exact libc build."),
        t("Remote vs local", "ASLR on remote — leaks required; local may disable for debugging."),
    ],
    "binary/heap-exploitation": [
        t("Identify allocator", "glibc dlmalloc vs jemalloc — techniques differ completely."),
        t("Heap visualization", "pwndbg `heap` and `bins` commands show layout during exploit dev."),
        t("Libc leak first", "Unsorted bin leak is classic — confirm before arbitrary write."),
        t("tcache poisoning", "Modern glibc — tcache is first target on 2.26+."),
        t("Match libc exactly", "Download target libc from server or package mirror."),
    ],
}
