from tips._base import t

SPECIALIZED_TIPS = {
    "blue-team/detection-engineering": [
        t("Start with ATT&CK", "Pick one technique sub-technique — write detection before broad coverage."),
        t("Sigma portability", "Write Sigma first, convert to Splunk/KQL — avoids vendor lock-in early."),
        t("Atomic Red Team validate", "Run matching atomic test — no alert means detection gap proven."),
        t("Tune false positives", "Baseline 7 days of logs before enabling production alerts."),
        t("Document data sources", "Detection without required log field is a false promise in SOC."),
    ],
    "blue-team/siem-log-analysis": [
        t("UTC everywhere", "Normalize all timestamps to UTC before building timelines."),
        t("Entity pivot", "Pick one user or host — pivot across DNS, proxy, auth, endpoint."),
        t("Rare process first", "Statistical outliers beat keyword searches for unknown malware."),
        t("Save queries", "Export working SPL/KQL as detection candidates."),
        t("Chain of custody", "Note who pulled logs and when for incident reports."),
    ],
    "blue-team/threat-hunting": [
        t("Hypothesis driven", "Start with intel: new CVE, odd DNS, or peer anomaly — not random searches."),
        t("Velociraptor scale", "Deploy hunt across fleet without RDPing to each host."),
        t("Baseline normal", "Know what good looks like before declaring evil."),
        t("Hunt to detection", "Every true positive hunt should become a permanent rule."),
        t("Time-box hunts", "4-hour hunts with clear success criteria beat endless scrolling."),
    ],
    "blue-team/incident-response": [
        t("Contain before eradicate", "Isolate host, disable account, block IOC — in that order."),
        t("Preserve volatile data", "Memory and netstat before reboot — order matters."),
        t("Comms template", "Pre-written stakeholder updates reduce panic during P1."),
        t("Don't wipe early", "Forensics needs disk — image before rebuild."),
        t("30-day watch", "Re-compromise often follows weak eradication — extend monitoring."),
    ],
    "blue-team/malware-analysis": [
        t("Hash first", "VirusTotal lookup before opening — may be known family."),
        t("Isolate the VM", "No host clipboard, no shared folders, snapshot before run."),
        t("Static then dynamic", "Strings and imports guide what to watch in sandbox."),
        t("YARA for family", "Write YARA from unique strings — share with SOC."),
        t("C2 safely", "Block egress or use INetSim — never let sample phone home to real C2.", "warning"),
    ],
    "cryptography/crypto-flaws": [
        t("grep for secrets", "Search repos for `AES_KEY`, `SECRET`, `BEGIN RSA` — still common."),
        t("JWT alg none", "Quick win on homegrown auth — test before deep crypto review."),
        t("ECB patterns", "Repeated blocks in ciphertext suggest ECB mode on structured data."),
        t("testssl.sh sweep", "Run on every hostname — weak TLS configs cluster on legacy apps."),
        t("Never roll your own", "Custom crypto protocols in source = high priority review."),
    ],
    "cryptography/padding-oracle": [
        t("Error differential", "Compare response size, status, and body on bad padding vs good."),
        t("padbuster automation", "`padbuster URL ciphertext 8` — block size 8 or 16."),
        t("Every encrypted field", "Cookies, URL params, hidden form fields — test all."),
        t("Lab only decrypt", "Decrypting live user sessions needs explicit authorization.", "warning"),
        t("Fix is AEAD", "Recommend AES-GCM or ChaCha20-Poly1305 — not just PKCS padding tweak."),
    ],
    "cryptography/tls-ssl": [
        t("testssl.sh full", "`testssl.sh --severity HIGH target:443` for actionable output."),
        t("Legacy clients", "Old Java/Android may force TLS 1.0 — document business need."),
        t("Cert name mismatch", "SAN omissions break more than expired certs in practice."),
        t("HSTS preload", "Missing HSTS on apex enables sslstrip in captive portals."),
        t("Internal CAs", "Corporate MITM proxies — distinguish misconfig from intentional inspection."),
    ],
    "devsecops/pipeline-security": [
        t("Fork PR secrets", "GitHub Actions secrets unavailable on forks — test poisoned PR paths."),
        t("OIDC over long-lived tokens", "Recommend `id-token: write` + cloud OIDC — no AWS keys in YAML."),
        t("PPE attacks", "Pull Request Target workflows run with base repo secrets — high risk."),
        t("Branch protection", "Require reviews and block force-push on default branch."),
        t("Artifact signing", "cosign/sigstore for images — verify in deploy stage."),
    ],
    "devsecops/iac-security": [
        t("checkov in PR", "Fail build on HIGH — don't only scan quarterly."),
        t("0.0.0.0/0 grep", "Search Terraform for open security groups and `Principal: *`."),
        t("State file secrets", "Terraform state may contain DB passwords — lock down S3 backend."),
        t("Drift detection", "Console changes bypass IaC — compare live vs code."),
        t("Fix snippets in report", "One-line HCL fix per finding speeds remediation."),
    ],
    "devsecops/supply-chain": [
        t("SBOM on release", "syft + grype in pipeline — block on critical CVEs."),
        t("Typosquat watch", "Monitor npm/PyPI names similar to internal packages."),
        t("cosign verify", "Enforce signature verification in admission controller."),
        t("Dependency confusion", "Private package names claimed on public registries — namespace packages."),
        t("Pin digests", "Image tags move — use `@sha256:` in production manifests."),
    ],
    "forensics/disk-memory": [
        t("Write-blocker always", "Never mount original evidence read-write."),
        t("Hash verify", "SHA-256 before and after imaging — document both."),
        t("Volatility profile", "Wrong Windows profile garbles output — identify OS build first."),
        t("Timeline UTC", "Autopsy + Plaso super timeline for court-ready chronology."),
        t("Chain of custody form", "Who, when, where, hash — every handoff documented."),
    ],
    "forensics/network": [
        t("Zeek for scale", "Wireshark for detail, Zeek for enterprise PCAP volume."),
        t("Beacon detection", "Regular interval connections — plot time delta in spreadsheet."),
        t("JA3/JA3S", "TLS fingerprint survives IP rotation."),
        t("DNS exfil", "Long TXT queries and rare domains in PCAP."),
        t("Privacy minimization", "Redact unrelated user traffic in shared PCAP extracts."),
    ],
    "forensics/cloud": [
        t("Pull logs fast", "CloudTrail retention defaults — export before expiry."),
        t("AssumeRole trail", "Attacker pivot often shows as cross-account AssumeRole."),
        t("GuardDuty correlation", "Use findings as index into raw CloudTrail events."),
        t("Region sweep", "Attackers create resources in unused regions."),
        t("IAM change timeline", "New access keys and policy attachments = priority events."),
    ],
    "growth/cve-research": [
        t("Diff the patch", "git diff between fixed and vulnerable commit isolates root cause."),
        t("KEV priority", "CISA KEV list = vendors already exploited in wild."),
        t("Minimal PoC", "Crash or info leak before full RCE — faster disclosure."),
        t("Vendor channel", "Use security@ or VDP — not public GitHub issue day one."),
        t("Isolated lab VM", "Never weaponize against production.", "warning"),
    ],
    "growth/writeups": [
        t("Impact first paragraph", "Lead with what attacker gains — not how you found it."),
        t("Redact aggressively", "PII, internal hostnames, and live tokens out of public posts."),
        t("Repro steps numbered", "Copy-paste friendly steps get more engagement and bounties."),
        t("Screenshots annotated", "Arrows on Burp screenshots save triage time."),
        t("Credit others", "Link prior art and collaborators — community remembers."),
    ],
    "iot/firmware-analysis": [
        t("binwalk extract", "`binwalk -e firmware.bin` — then grep squashfs for `passwd`."),
        t("Emulate carefully", "Firmadyne/QEMU when architecture matches — ARM vs MIPS."),
        t("Hardcoded telnet", "root:12345 still appears in consumer IoT."),
        t("Unsigned updates", "MITM update channel = full device compromise PoC."),
        t("Vendor disclosure", "Consumer device bugs need coordinated disclosure timeline."),
    ],
    "iot/hardware-interfaces": [
        t("UART baud scan", "Try 115200, 57600, 38400 — multimeter finds TX/RX/GND."),
        t("3.3V vs 5V", "Wrong voltage fries boards — confirm before connecting.", "warning"),
        t("Boot interrupt", "Spam key during power-on for U-Boot or CFE shell."),
        t("SPI flash dump", "flashrom or chip programmer when UART locked."),
        t("Photo pinout", "Document pads for report — future you will thank you."),
    ],
    "osint/people-org": [
        t("theHarvester baseline", "Emails and subdomains in one command — start here."),
        t("Email format", "firstname.lastname@corp.com enables targeted sims (authorized only)."),
        t("Cross-verify", "One LinkedIn profile != confirmed employee — corroborate."),
        t("Legal boundaries", "OSINT for defense and authorized red team — not harassment."),
        t("Date your intel", "People change roles — stale org charts mislead."),
    ],
    "osint/data-breach-search": [
        t("HIBP API domain", "Check corporate domain exposure — defensive notification only."),
        t("Never credential stuff", "Breach data for unauthorized login is illegal.", "warning"),
        t("Force reset workflow", "Pair exposed emails with mandatory MFA enrollment."),
        t("Password policy", "Reuse from personal breaches hits corporate accounts."),
        t("Monitor continuously", "One-time check misses new breaches — automate alerts."),
    ],
    "social-engineering/phishing": [
        t("gophish metrics", "Click rate and submit rate — not individual shaming."),
        t("Legal sign-off", "Written approval naming date range and target groups."),
        t("Realistic not cruel", "Urgent payroll lure works — fake termination does harm."),
        t("Landing on isolated domain", "Use lookalike you control — not real login page clone on prod."),
        t("Delete captured creds", "Test passwords destroyed after debrief."),
    ],
    "social-engineering/pretexting": [
        t("Stop phrase agreed", "Target can say codeword to verify caller with security."),
        t("Record laws", "Two-party consent states — know before recording calls."),
        t("Low info goal", "One fact per call — multi-question raises suspicion."),
        t("Callback verification", "Train client to call known IT number back."),
        t("Debrief without names", "Aggregate lessons — protect individuals."),
    ],
    "reporting/vulnerability-reports": [
        t("Title = impact", "`Account takeover via IDOR on /api/user` beats `IDOR found`."),
        t("HTTP raw request", "Paste full request/response — triagers reproduce faster."),
        t("Severity justification", "Map to program rubric with business impact sentence."),
        t("One video minute", "Screen recording under 60s — trim recon noise."),
        t("Respond fast", "Quick answers to analyst questions prevent duplicate/duplicate-close."),
    ],
    "secure-code-review/sast": [
        t("semgrep auto rules", "`semgrep --config p/owasp-top-ten` on every PR."),
        t("Triage by reachability", "Sink without source path = likely false positive."),
        t("Auth hotspots", "grep `isAdmin`, `role`, `permission` — manual review there."),
        t("CodeQL path queries", "Data flow from `getParameter` to SQL execution."),
        t("File:line in ticket", "Developers fix faster with exact location and fix snippet."),
    ],
    "secure-code-review/threat-modeling": [
        t("Data flow diagram", "Draw trust boundaries before STRIDE — boxes and arrows first."),
        t("STRIDE per element", "One worksheet row per component — don't batch threats."),
        t("Store in git", "Threat model YAML/MD versioned with architecture changes."),
        t("Test cases from threats", "Each high threat becomes a security test case in QA."),
        t("OWASP Threat Dragon", "Free tool exports models shareable with dev teams."),
    ],
    "web3/smart-contracts": [
        t("Fork mainnet locally", "Foundry `anvil --fork-url` — never test exploits on live chain.", "warning"),
        t("slither first", "Static analysis catches reentrancy and access control in minutes."),
        t("Check upgrade proxy", "UUPS/Transparent proxy admin key = full drain if compromised."),
        t("Invariant fuzzing", "Echidna `echidna` on protocol invariants — balance never negative."),
        t("Immunefi scope", "Out-of-scope contracts and known issues listed — read first."),
    ],
    "web3/wallet-dapp": [
        t("Transaction simulation", "MetaMask/Rabby simulate — test what user actually signs."),
        t("Infinite approval", "USDT `approve(max)` — report clear revocation steps."),
        t("Address poisoning", "UI shows first/last chars — users send to lookalike addresses."),
        t("Clone dApp domains", "Homoglyph domains + wallet connect — user education angle."),
        t("Test on testnet", "Sepolia/Goerli forks for UI bugs without real funds."),
    ],
    "automation/js-analysis": [
        t("linkfinder pipeline", "Every JS URL through linkfinder — APIs hide in minified bundles."),
        t("secretfinder pass", "AWS keys and internal URLs in `app.*.js` chunk files."),
        t("katana crawl", "`katana -u target -jc` extracts JS-linked endpoints."),
        t("Version diff", "Save JS weekly — new routes appear before public changelog."),
        t("Scope filter", "Auto-found hosts may be CDN or third-party — verify in program scope."),
    ],
    "automation/diffing": [
        t("Baseline release", "Export endpoints and OpenAPI before each deploy."),
        t("New params only", "Diff highlights new attack surface — prioritize manual test."),
        t("Auth regression", "Removed middleware on old routes — common on refactors."),
        t("nuclei on delta", "Scan only new URLs — faster and less noisy."),
        t("Changelog correlation", "Map security-relevant commits to endpoint diff."),
    ],
    "automation/scope-tooling": [
        t("bbscope export", "`bbscope h1 -t TOKEN -p program` — canonical scope file."),
        t("Wildcard regex", "Convert `*.target.com` to testable patterns for automation."),
        t("Out-of-scope blocklist", "Explicit exclusions prevent accidental bans."),
        t("Git-track scope", "Commit scope.json — team shares same boundaries."),
        t("Scheduled refresh", "Cron weekly scope pull — programs add assets often."),
    ],
}
