"""Detailed vulnerability content for API and authentication topics."""

API_AUTH_CONTENT: dict[str, dict[str, str]] = {
    "api/graphql": {
        "how_it_works": (
            "GraphQL exposes a single HTTP endpoint (typically `/graphql`) where clients "
            "send declarative queries describing exactly which fields and nested objects they "
            "need. Unlike REST, the server resolves a graph of types—`Query`, `Mutation`, and "
            "`Subscription`—and fetches only requested fields. This flexibility creates a "
            "distinct attack surface:\n\n"
            "- **Schema introspection** (`__schema`, `__type`) can reveal the entire data model, "
            "including admin-only mutations and sensitive fields.\n"
            "- **Depth and complexity** are unbounded unless the server enforces limits; deeply "
            "nested queries can cause denial of service or expensive database joins.\n"
            "- **Batching and aliases** let attackers send dozens of operations in one HTTP "
            "request, often bypassing per-request rate limits.\n"
            "- **Authorization is field-level**, not route-level: a resolver may check auth on "
            "`getUser` but forget `user.email` or nested `user.orders.paymentMethod`.\n"
            "- **Persisted queries, subscriptions, and file uploads** add secondary endpoints "
            "that are easy to misconfigure.\n\n"
            "Common stacks (Apollo Server, Hasura, Strawberry, gqlgen) differ in default "
            "introspection, batching, and depth-limit behavior—always test the deployed "
            "configuration, not assumptions from the framework docs."
        ),
        "exploitation": (
            "1. **Discover the endpoint** — Probe `/graphql`, `/api/graphql`, `/v1/graphql`, "
            "and check JS bundles, mobile traffic, and `robots.txt` for references.\n"
            "2. **Confirm GraphQL** — POST a minimal query such as "
            "`{\"query\":\"{ __typename }\"}`; a JSON body with `data` or `errors` confirms GraphQL.\n"
            "3. **Run introspection** — If enabled, dump the schema with standard introspection "
            "queries or tools like `clairvoyance`, `graphql-cop`, or Burp's InQL extension.\n"
            "4. **Map authorization gaps** — For each sensitive type/mutation, replay requests "
            "as an unauthenticated user, low-privilege user, and victim user (IDOR via global IDs "
            "or relay cursors).\n"
            "5. **Test batching and aliases** — Send arrays of login/OTP mutations or alias "
            "multiple `user(id: N)` fields in one query to bypass rate limits.\n"
            "6. **Stress depth/complexity** — Gradually increase nesting (`user { friends { "
            "friends { ... } } }`) and argument fan-out to find DoS or data-leak via "
            "over-fetching.\n"
            "7. **Hunt debug surfaces** — GraphiQL, GraphQL Playground, Voyager, and "
            "Apollo Studio sandbox endpoints often ship enabled in staging.\n"
            "8. **Document impact** — Show concrete data exposure or auth bypass with minimal "
            "reproducible queries; note whether WAF/CDN blocks introspection but allows "
            "equivalent hand-crafted queries."
        ),
        "defense": (
            "- **Disable introspection in production** (or restrict to authenticated admin roles "
            "behind network controls); treat schema as sensitive intellectual property.\n"
            "- **Enforce query cost limits**: max depth, max complexity/aliases, pagination "
            "defaults, and timeouts on resolver execution.\n"
            "- **Apply authorization at every resolver**, including nested fields and list "
            "items—use a consistent policy layer (e.g., field-level ACLs, Open Policy Agent).\n"
            "- **Rate-limit by operation and user**, not only by HTTP request; reject or split "
            "batched arrays when abuse is detected.\n"
            "- **Disable batching** on authentication-sensitive endpoints if not required.\n"
            "- **Use persisted/allowlisted queries** for mobile and public clients where feasible.\n"
            "- **Log query names, complexity scores, and anomalies**; alert on introspection "
            "attempts and high-cost queries.\n"
            "- **Remove GraphiQL/Playground** from internet-facing deployments; follow the "
            "[OWASP GraphQL Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html)."
        ),
    },
    "api/graphql/introspection": {
        "how_it_works": (
            "GraphQL introspection is a built-in meta-query capability defined in the GraphQL "
            "specification. Clients can query special fields `__schema` and `__type` to discover "
            "all types, fields, arguments, enums, interfaces, and directives the server "
            "supports. A standard introspection query recursively walks `queryType`, "
            "`mutationType`, and `subscriptionType`, exporting names like `adminDeleteUser`, "
            "`internalApiKey`, or `ssn` that were never documented publicly.\n\n"
            "Introspection is invaluable during development but dangerous when exposed to "
            "attackers: it turns black-box API testing into full schema-driven fuzzing. Some "
            "frameworks disable it by default in production; others require explicit "
            "configuration. WAF rules that block the word `__schema` are brittle—attackers can "
            "use fragments, whitespace tricks, or pre-built schema files from CI leaks."
        ),
        "exploitation": (
            "1. **Send the standard introspection query** — Use Burp, `curl`, or `graphql-cli` "
            "with the full `IntrospectionQuery` payload against `/graphql`.\n"
            "2. **Try variants if blocked** — Alternate HTTP methods (GET with `query` param), "
            "different `Content-Type` values, or POST to `/graphql?query=` endpoints used by "
            "some CDNs.\n"
            "3. **Check staging and old hosts** — Staging, preview, and legacy subdomains often "
            "leave introspection enabled while production disables it.\n"
            "4. **Use blind schema recovery** — If introspection is disabled, tools like "
            "`clairvoyance` infer the schema from error messages (`Cannot query field \"foo\" on "
            "type \"Query\"`).\n"
            "5. **Prioritize high-value types** — Search exported SDL for `Mutation` names "
            "containing `admin`, `internal`, `delete`, `export`, `impersonate`, `password`.\n"
            "6. **Cross-reference with auth** — For each discovered mutation, test without "
            "tokens, with expired tokens, and across user roles.\n"
            "7. **Export for automation** — Feed the schema into `graphql-voyager`, custom "
            "fuzzers, or InQL to systematically test every field."
        ),
        "defense": (
            "- **Turn off introspection in production** via server config (Apollo: "
            "`introspection: false`; Hasura: disable from console settings).\n"
            "- **Never rely on WAF keyword blocking alone**; enforce at the GraphQL execution layer.\n"
            "- **Restrict schema access** to CI, schema registry, and internal VPN if developers "
            "need SDL at runtime.\n"
            "- **Return generic errors** in production to hinder clairvoyance-style inference.\n"
            "- **Audit deployments** so preview environments are not publicly routable without "
            "auth.\n"
            "- **Monitor for `__schema` and `__type` in request bodies** and alert on spikes."
        ),
    },
    "api/graphql/batching": {
        "how_it_works": (
            "Many GraphQL servers accept an **array of operations** in a single HTTP POST body, "
            "executing them sequentially or in parallel and returning an array of results. "
            "Libraries such as Apollo Server enable batching by default in some versions. "
            "Similarly, **query aliases** let multiple identical or distinct operations run in "
            "one request:\n\n"
            "```graphql\n"
            "mutation {\n"
            "  a: login(user: \"victim@corp.com\", pass: \"0000\") { token }\n"
            "  b: login(user: \"victim@corp.com\", pass: \"0001\") { token }\n"
            "  # ... dozens more aliases\n"
            "}\n"
            "```\n\n"
            "Rate limiters and WAFs often count **HTTP requests**, not **GraphQL operations**. "
            "An attacker can brute-force passwords, OTP codes, or coupon tokens by packing "
            "hundreds of attempts into one request that appears as a single API call in logs."
        ),
        "exploitation": (
            "1. **Identify batch support** — POST `[{\"query\":\"...\"},{\"query\":\"...\"}]` "
            "and observe whether the response is a JSON array.\n"
            "2. **Baseline rate limits** — Send single login mutations until throttled; record "
            "HTTP 429 thresholds and lockout behavior.\n"
            "3. **Replay as a batch** — Wrap 50–100 login or `verifyOtp` mutations in one "
            "array; compare success rate vs. individual requests.\n"
            "4. **Use aliases for fan-out** — Brute force without arrays if the server rejects "
            "batch arrays but allows aliases on one mutation.\n"
            "5. **Combine with credential stuffing** — Parallel `login` across many users in "
            "one batch to evade per-IP limits.\n"
            "6. **Measure server-side impact** — Note DB connection pool exhaustion or CPU spikes "
            "for DoS reporting.\n"
            "7. **Capture evidence** — Show one HTTP request attempting N passwords and "
            "receiving N responses without throttling."
        ),
        "defense": (
            "- **Disable query batching** on public endpoints unless there is a clear need.\n"
            "- **Rate-limit by GraphQL operation count and cost**, not only per HTTP request.\n"
            "- **Apply stricter limits to auth mutations** (`login`, `register`, `resetPassword`, "
            "`verifyOtp`) including per-user and per-IP backoff.\n"
            "- **Cap aliases per query** and reject documents exceeding complexity budgets.\n"
            "- **Use CAPTCHA or proof-of-work** after a small number of failed auth attempts, "
            "regardless of batching.\n"
            "- **Log and alert** when a single request contains multiple auth mutations."
        ),
    },
    "api/versioning": {
        "how_it_works": (
            "APIs evolve through versioned paths (`/v1/`, `/v2/`), headers (`Accept-Version`, "
            "`X-Api-Version`), query parameters, or separate hostnames (`api-old.example.com`). "
            "Teams frequently ship stricter auth, input validation, and rate limiting on new "
            "versions while **legacy versions remain online** for mobile apps, partners, or "
            "internal tools.\n\n"
            "This creates a **version skew** vulnerability class (related to OWASP API #9 "
            "Improper Inventory Management): attackers target deprecated endpoints that still "
            "accept weak API keys, lack MFA checks, expose verbose errors, or skip object-level "
            "authorization added only in newer code paths."
        ),
        "exploitation": (
            "1. **Enumerate versions** — Fuzz `/v1`, `/v2`, `/v3`, `/beta`, `/internal`, "
            "`/mobile`, `/legacy`, and date-stamped paths (`/2023-01/`).\n"
            "2. **Compare OpenAPI/Swagger** — Diff `/swagger/v1/swagger.json` vs `/v2/` for "
            "removed auth requirements or extra endpoints.\n"
            "3. **Replay attacks across versions** — Take a blocked IDOR or auth bypass payload "
            "from `/v2/users/123` and retry on `/v1/users/123`.\n"
            "4. **Inspect mobile apps** — Hardcoded base URLs often point at older API versions "
            "with weaker controls.\n"
            "5. **Check version headers** — Send `X-Api-Version: 1` on routes that default to "
            "v2 behavior.\n"
            "6. **Hunt debug builds** — `/v1/debug`, `/v2/test`, and feature-flagged routes "
            "may exist only in specific versions.\n"
            "7. **Document differential behavior** — Show the same token or none at all "
            "succeeding only on the legacy path."
        ),
        "defense": (
            "- **Maintain an authoritative API inventory** with owner, auth model, and sunset date "
            "for every version.\n"
            "- **Deprecate aggressively**: return `Sunset` headers, monitor traffic, then "
            "decommission old versions on a fixed timeline.\n"
            "- **Backport critical security fixes** to all supported versions or force client "
            "upgrades.\n"
            "- **Apply consistent authorization middleware** shared across versions, not "
            "copy-pasted per router.\n"
            "- **Block internet access** to internal/beta versions; require VPN or mTLS.\n"
            "- **Automate contract tests** so new security controls cannot ship only in the "
            "latest route tree."
        ),
    },
    "api/shadow-zombie-apis": {
        "how_it_works": (
            "**Shadow APIs** are undocumented endpoints—microservices, serverless functions, "
            "admin panels, or feature branches reachable in production but absent from official "
            "docs. **Zombie APIs** are formerly documented services that should have been "
            "retired but still accept traffic (old load balancer rules, forgotten containers, "
            "or DNS to decommissioned environments that were cloned).\n\n"
            "They often lack WAF coverage, OAuth scopes, audit logging, and patch cadence. "
            "Discovery vectors include JavaScript bundles, mobile apps, proxy logs, "
            "certificate transparency, cloud API gateways, and leaked OpenAPI files in "
            "`.git` or S3 buckets."
        ),
        "exploitation": (
            "1. **Mine client-side code** — Run `LinkFinder`, `katana`, and `nuclei` on JS "
            "bundles for `/api/`, `/internal/`, GraphQL, and WebSocket URLs.\n"
            "2. **Intercept mobile traffic** — Proxy iOS/Android apps to find alternate base "
            "URLs and hidden REST/gRPC backends.\n"
            "3. **Scan for spec leaks** — Probe `/swagger.json`, `/openapi.yaml`, `/api-docs`, "
            "`/redoc`, and `/.well-known/` paths.\n"
            "4. **Review infrastructure** — Cloud API Gateway stages, Lambda function URLs, and "
            "Kubernetes ingress rules may expose services engineers forgot.\n"
            "5. **Use historical data** — `gau`, Wayback Machine, and breach dumps for old "
            "subdomains and paths.\n"
            "6. **Diff deployments** — Compare responses before/after releases; new routes "
            "sometimes appear without documentation.\n"
            "7. **Test without auth** — Shadow endpoints frequently ship before auth middleware "
            "is wired up.\n"
            "8. **Chain findings** — A zombie admin API on `staging-api.example.com` may share "
            "production credentials."
        ),
        "defense": (
            "- **Central API gateway** with mandatory auth, logging, and schema registration for "
            "all public traffic.\n"
            "- **Automated asset inventory** tied to CI/CD—block deploy if routes are not "
            "registered.\n"
            "- **Decommission runbooks**: remove DNS, certs, LB rules, and cloud resources "
            "together; verify with external scans.\n"
            "- **Restrict internal hostnames** to private networks; never reuse production "
            "secrets on shadow environments.\n"
            "- **Scan repositories and buckets** for OpenAPI leaks; rotate any exposed keys.\n"
            "- **Continuous external attack surface monitoring** (EASM) to detect unknown "
            "endpoints early."
        ),
    },
    "api/grpc-protobuf": {
        "how_it_works": (
            "gRPC uses HTTP/2 with Protocol Buffers (protobuf) for compact binary messages. "
            "Services expose RPC methods (`/package.Service/Method`) instead of REST paths. "
            "**gRPC server reflection** allows clients to list services and message types at "
            "runtime—similar to GraphQL introspection. Many internal microservices speak gRPC "
            "on ports like 50051, sometimes exposed through gRPC-Web, Envoy transcoding, or "
            "misconfigured load balancers.\n\n"
            "Protobuf is not encryption: messages can be decoded with a `.proto` file or "
            "inferred via reflection. Metadata headers carry JWTs and API keys; mTLS is "
            "optional and often missing on \"internal\" networks reachable from SSRF or VPN gaps."
        ),
        "exploitation": (
            "1. **Discover gRPC ports** — Scan for 50051, 443 with HTTP/2, and `content-type: "
            "application/grpc` responses.\n"
            "2. **Enable reflection** — `grpcurl -plaintext host:50051 list` or `grpcui` to "
            "enumerate services when reflection is on.\n"
            "3. **Obtain `.proto` files** — From repos, APKs, reflection, or transcoding "
            "gateway configs; use `protoc` or Burp gRPC assistant to craft messages.\n"
            "4. **Call methods without auth** — Invoke `GetUser`, `Admin`, `Export` RPCs with "
            "empty or forged metadata.\n"
            "5. **Fuzz fields** — Protobuf parsers may ignore unknown fields; test oversized "
            "strings, negative IDs, and enum overflows.\n"
            "6. **Test metadata tokens** — Replay JWTs across services; try missing/alternate "
            "`:authority` headers.\n"
            "7. **Exploit gRPC-Web bridges** — Browser-facing transcoding may weaken auth "
            "applied on native gRPC hops.\n"
            "8. **SSRF to gRPC** — If an app can reach internal gRPC, pivot from HTTP SSRF to "
            "binary RPC calls."
        ),
        "defense": (
            "- **Disable server reflection in production**; distribute protos only through "
            "secure artifact registries.\n"
            "- **Require mTLS and/or signed JWTs** on every RPC; enforce per-method authorization.\n"
            "- **Do not expose raw gRPC to the internet**; use API gateways with policy enforcement.\n"
            "- **Network segmentation** so only trusted meshes (service mesh sidecars) can reach "
            "gRPC backends.\n"
            "- **Validate all protobuf fields** server-side; never trust client-supplied IDs for "
            "access control.\n"
            "- **Log RPC method, peer identity, and latency**; alert on reflection probes and "
            "unauthenticated calls."
        ),
    },
    "authentication/password-reset": {
        "how_it_works": (
            "Password reset flows typically: (1) user submits an email, (2) server generates a "
            "one-time token and emails a link, (3) user clicks the link and sets a new password. "
            "Weaknesses appear at every step: **predictable tokens** (timestamp, user ID, weak "
            "PRNG), **tokens that never expire or are reusable**, **user enumeration** via "
            "different responses, **Host header poisoning** that embeds attacker domains in "
            "reset links, **parameter tampering** (`email`, `userId`, `account`), and **race "
            "conditions** between token validation and password update.\n\n"
            "Some implementations leak tokens in Referer headers, browser history, or server "
            "logs; others allow resetting another user's password when only the token is required "
            "without re-binding to the initiating session."
        ),
        "exploitation": (
            "1. **Request reset for your account** — Capture the token format, length, entropy, "
            "and URL structure.\n"
            "2. **Test predictability** — Request multiple tokens; check for sequential IDs, "
            "base64-encoded emails, or HMAC with weak secrets.\n"
            "3. **Host / X-Forwarded-Host poisoning** — Submit reset with `Host: evil.com` and "
            "see if the email link points to the attacker domain.\n"
            "4. **Token reuse** — Complete a reset, then reuse the same link; try using one "
            "token twice in parallel tabs.\n"
            "5. **Change email parameter** — Modify `email` or `user_id` in POST body while using "
            "another user's token (or none).\n"
            "6. **Race conditions** — Send concurrent reset-completion requests with the same "
            "token using Burp Turbo Intruder.\n"
            "7. **Enumerate users** — Compare timing, status codes, and message text for valid "
            "vs invalid accounts.\n"
            "8. **Intercept delivery** — If SMS reset, test SIM-swap social paths; if security "
            "questions exist, test weak answers.\n"
            "9. **Check mobile deep links** — Custom URL schemes may pass tokens without HTTPS."
        ),
        "defense": (
            "- **Generate tokens with CSPRNG** (≥128 bits); store only a hashed token server-side.\n"
            "- **Single-use, short TTL** (15–60 minutes); invalidate all sessions after reset.\n"
            "- **Bind tokens to user agent or session** where UX allows; require current password "
            "for logged-in users.\n"
            "- **Ignore client Host headers**; build reset URLs from a configured canonical base URL.\n"
            "- **Uniform responses** — always return \"If an account exists, we sent email\".\n"
            "- **Rate-limit reset requests** per email and IP; monitor brute-force on token endpoints.\n"
            "- **Use HTTPS-only links**; add `Referrer-Policy: no-referrer` on reset pages.\n"
            "- Follow the [OWASP Forgot Password Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html)."
        ),
    },
    "authentication/sso-saml": {
        "how_it_works": (
            "Single Sign-On (SSO) federates authentication to an Identity Provider (IdP). "
            "**SAML 2.0** flows exchange XML assertions—often via POST bindings—containing "
            "attributes like email and group membership. The Service Provider (SP) must "
            "**validate XML signatures**, check `NotBefore`/`NotOnOrAfter`, match `Audience`, "
            "and prevent **XML signature wrapping (XSW)** attacks where attackers smuggle "
            "unsigned assertions alongside valid signed copies.\n\n"
            "**OAuth 2.0 / OpenID Connect** variants introduce `redirect_uri` validation bugs, "
            "authorization code interception, **mix-up attacks** (confusing codes between "
            "clients), and weak `state`/`nonce` handling. Misconfigured SAML metadata, "
            "certificate rollover, and unsigned `Response` elements are common in enterprise "
            "integrations."
        ),
        "exploitation": (
            "1. **Capture a legitimate SAML Response** — Use Burp during login; note signature "
            "placement, `NameID`, `Conditions`, and `Recipient`.\n"
            "2. **Test signature wrapping** — Duplicate assertions, move signatures, or inject "
            "unsigned assertions with attacker `NameID` (tools: SAML Raider, `samltool`).\n"
            "3. **Tamper with attributes** — Modify `Role`, `Groups`, or `email` fields if "
            "signature verification is flawed or only signs part of the document.\n"
            "4. **Replay assertions** — Resend captured responses; check if `InResponseTo` and "
            "timestamps are enforced.\n"
            "5. **OAuth redirect abuse** — Open redirect in `redirect_uri`, subdomain takeover "
            "on allowed callback URLs, or path traversal (`/callback/../evil`).\n"
            "6. **Mix-up / confusion** — Swap authorization codes between mobile and web client "
            "IDs if the token endpoint does not bind `client_id`.\n"
            "7. **Metadata poisoning** — If you can supply IdP metadata URL, point SP at "
            "attacker-controlled signing keys.\n"
            "8. **Downgrade flows** — Force SAML instead of stronger OIDC, or disable encryption "
            "if both are optional."
        ),
        "defense": (
            "- **Strictly validate SAML signatures** on the assertion or entire response per "
            "library best practice; reject unsigned assertions.\n"
            "- **Use well-tested libraries** (python3-saml, OneLogin toolkit) and keep them "
            "patched against XSW variants.\n"
            "- **Enforce one-time use** of assertions (`InResponseTo`, short `NotOnOrAfter`, "
            "replay caches).\n"
            "- **Pin IdP certificates**; monitor metadata fetch endpoints for tampering.\n"
            "- **OAuth/OIDC**: exact-match `redirect_uri` allowlists, PKCE for public clients, "
            "mandatory `state` and `nonce`.\n"
            "- **Rotate keys safely**; log failed signature validations and anomalous attribute "
            "changes.\n"
            "- Review [OWASP SAML Security guidance](https://owasp.org/www-community/vulnerabilities/SAML_Security_Cheat_Sheet)."
        ),
    },
    "authentication/passwordless": {
        "how_it_works": (
            "Passwordless authentication replaces passwords with **magic links** (email URLs "
            "with embedded tokens), **OTP codes** (SMS/email/TOTP), or **WebAuthn/FIDO2 "
            "passkeys** (public-key cryptography bound to origin and challenge). Each mechanism "
            "has distinct risks:\n\n"
            "- Magic links: token entropy, transport security, device sharing, open redirects on "
            "landing URLs.\n"
            "- OTP: short code brute force, race conditions, SIM swapping, lack of attempt limits.\n"
            "- WebAuthn: incorrect `rpId` validation, missing challenge binding, permissive "
            "`userVerification`, and account enumeration via credential ID lookup.\n\n"
            "Because there is no password, **the token or authenticator becomes the sole "
            "secret**—any guessable or interceptable factor fully compromises the account."
        ),
        "exploitation": (
            "1. **Magic link analysis** — Request a link; inspect token length, encoding, and "
            "whether it works after multiple uses or from different IPs.\n"
            "2. **Brute-force OTP** — If 4–6 digit codes, attempt all combinations with "
            "parallel requests; test whether lockout applies per session vs per IP.\n"
            "3. **Bypass delivery** — Register with attacker-controlled email/phone on victim "
            "alias (plus addressing, disposable domains) if verification is weak.\n"
            "4. **Fixation** — Start login on attacker device, trick victim into completing "
            "WebAuthn on attacker's session if challenges are not bound.\n"
            "5. **Enumerate accounts** — Different errors for registered vs unregistered emails "
            "or WebAuthn credential IDs.\n"
            "6. **Race OTP validation** — Submit the same code simultaneously from multiple "
            "clients before invalidation.\n"
            "7. **Deep link hijacking** — Mobile apps handling magic links via intents may leak "
            "tokens to other apps.\n"
            "8. **WebAuthn downgrade** — Force `userVerification: discouraged` or cross-origin "
            "flows if the server allows it."
        ),
        "defense": (
            "- **High-entropy, single-use tokens** for magic links; expire within minutes.\n"
            "- **Rate-limit OTP verification** aggressively; use 6+ digit or alphanumeric codes "
            "with lockout and backoff.\n"
            "- **Bind challenges to session** for WebAuthn; verify `origin`, `rpId`, and "
            "`challenge` server-side.\n"
            "- **Require user verification** (biometric/PIN) for sensitive accounts.\n"
            "- **Uniform messaging** to prevent account enumeration.\n"
            "- **Prefer WebAuthn over SMS OTP** where possible; monitor SIM-swap risk for SMS.\n"
            "- **Invalidate sessions** after passwordless login on new devices; notify users of "
            "new sign-ins.\n"
            "- See [WebAuthn Guide](https://webauthn.guide/) for implementation details."
        ),
    },
    "authentication/jwt": {
        "how_it_works": (
            "JSON Web Tokens (JWTs) are compact, signed (or MAC'd) claims objects, typically "
            "`header.payload.signature` in Base64url. The header declares `alg` (HS256, RS256, "
            "etc.); the payload holds claims like `sub`, `role`, and `exp`. Servers verify "
            "integrity using a shared secret (HMAC) or public key (RSA/ECDSA).\n\n"
            "Common flaws:\n"
            "- **`alg: none`** — libraries that accept unsigned tokens.\n"
            "- **Algorithm confusion** — RS256 public key used as HMAC secret (`alg: HS256`).\n"
            "- **Weak HMAC secrets** — brute-forced `secret`, `password`, `changeme`.\n"
            "- **`jku` / `x5u` / `kid` abuse** — server fetches attacker-controlled keys.\n"
            "- **Missing `exp` / `nbf` validation** and accepting tokens after logout.\n"
            "- **Sensitive data in payload** — JWTs are base64, not encrypted, unless JWE is used."
        ),
        "exploitation": (
            "1. **Decode the token** — Inspect header and payload in Burp or `jwt.io` (use only "
            "for public tokens, not production secrets).\n"
            "2. **Test `alg: none`** — Change algorithm to `none` and strip the signature; try "
            "variants `None`, `NONE`.\n"
            "3. **Key confusion** — If RS256, embed the public key in an HS256 token and sign "
            "with it (`jwt_tool -X k`).\n"
            "4. **Brute-force HMAC** — `hashcat -a 0 -m 16500 jwt.txt wordlist.txt` or "
            "`jwt_tool -C -d wordlist.txt`.\n"
            "5. **Tamper claims** — Change `role` to `admin`, `sub` to another user ID after "
            "forging a valid signature.\n"
            "6. **`jku` injection** — Point `jku` to attacker-hosted JWK set; host matching "
            "public key.\n"
            "7. **`kid` manipulation** — SQL injection or path traversal in `kid` lookup "
            "(`../../../../dev/null` for empty HMAC secret).\n"
            "8. **Replay expired tokens** — Remove `exp` if verification is lax; test tokens "
            "after password change.\n"
            "9. **Cross-service replay** — Use tokens intended for API A against API B if "
            "audience is not checked."
        ),
        "defense": (
            "- **Allowlist algorithms** server-side; never trust the header's `alg` blindly.\n"
            "- **Reject `none`** and enforce asymmetric verification with pinned public keys.\n"
            "- **Use strong secrets** (≥256-bit random) for HMAC; prefer RS256/ES256 for "
            "multi-service setups.\n"
            "- **Validate all standard claims**: `exp`, `nbf`, `iss`, `aud`; use short TTLs and "
            "refresh tokens.\n"
            "- **Disable `jku`/`x5u` fetching** or pin keys; sanitize `kid` resolution (no "
            "filesystem/SQL lookups on attacker input).\n"
            "- **Store revocation state** for logout and compromise; do not put secrets or PII in "
            "payloads.\n"
            "- **Rotate keys** with `kid` versioning; monitor for signature failures and "
            "algorithm anomalies.\n"
            "- Reference [PortSwigger JWT attacks](https://portswigger.net/web-security/jwt) for "
            "test cases to block."
        ),
    },
}
