"""Detailed vulnerability content for infrastructure, network, cloud, and blue-team topics."""

INFRA_CONTENT: dict[str, dict[str, str]] = {
    "bug-bounty/recon": {
        "how_it_works": (
            "Reconnaissance is the systematic process of mapping a target's attack surface before "
            "vulnerability testing begins. In bug bounty programs, recon combines **passive "
            "intelligence** (data already published by third parties) with **active probing** "
            "(direct interaction with in-scope assets under program rules).\n\n"
            "A typical pipeline flows through four layers:\n\n"
            "1. **Scope validation** — Parse program rules for domains, wildcards, IP ranges, "
            "mobile apps, and out-of-scope exclusions.\n"
            "2. **Passive collection** — Certificate transparency (crt.sh), DNS history, "
            "search engines, GitHub code search, Shodan/Censys, Wayback Machine, and breach "
            "databases surface hosts without touching the target directly.\n"
            "3. **Active enumeration** — Subdomain brute force, DNS resolution, port scanning, "
            "and HTTP probing confirm what is live.\n"
            "4. **Prioritization** — Rank assets by technology stack, authentication state, "
            "environment type (prod vs staging), and historical vulnerability density.\n\n"
            "Effective recon produces an **asset inventory** that feeds downstream testing "
            "(nuclei, manual review, API mapping). Attackers and researchers share the same "
            "tooling; the difference is authorization and responsible disclosure."
        ),
        "exploitation": (
            "1. **Import scope** — Use `bbscope` or program JSON exports to build an authoritative "
            "domain/IP list; never test out-of-scope assets.\n"
            "2. **Run passive first** — `subfinder -d target.com -all`, `amass enum -passive`, "
            "`gau target.com`, and `waybackurls` to avoid early active noise.\n"
            "3. **Resolve and deduplicate** — Pipe subdomains through `puredns` or `dnsx` to "
            "filter wildcards and dead records.\n"
            "4. **Probe live services** — `httpx -l subs.txt -title -status-code -tech-detect "
            "-follow-redirects` builds a prioritized web target list.\n"
            "5. **Scan for exposures** — `nuclei -l live.txt -t exposures/ -t misconfiguration/` "
            "catches default panels, `.git` leaks, and misconfigured buckets.\n"
            "6. **Correlate with acquisitions** — Search parent company domains and forgotten "
            "brands for shadow infrastructure.\n"
            "7. **Track changes** — Re-run pipelines weekly; new subdomains and JS routes often "
            "precede public bug fixes.\n"
            "8. **Document everything** — Maintain a spreadsheet or Notion board linking each "
            "asset to tests performed and findings."
        ),
        "defense": (
            "- **Maintain an authoritative asset inventory** updated from DNS, cloud consoles, "
            "and CMDB; unknown assets are the primary recon win for attackers.\n"
            "- **Monitor certificate transparency** and alert on new subdomains under your "
            "brand; revoke or claim dangling DNS before takeover.\n"
            "- **Reduce passive leakage** — Remove internal hostnames from public repos, job "
            "postings, and marketing pages.\n"
            "- **Harden non-production environments** — Staging and dev hosts are recon magnets; "
            "require VPN, IP allowlists, or SSO.\n"
            "- **Deploy external attack surface management (EASM)** to continuously discover what "
            "attackers see from the internet.\n"
            "- **Rate-limit and alert on aggressive scanning** from unexpected ASNs while "
            "accepting good-faith researcher traffic per program policy.\n"
            "- **Run your own recon pipeline internally** on a schedule; fix exposures before "
            "they appear on HackerOne."
        ),
    },
    "bug-bounty/subdomain-enumeration": {
        "how_it_works": (
            "Subdomain enumeration discovers hostnames under a root domain (`*.target.com`) "
            "that expand the attack surface beyond the primary website. Hostnames are found "
            "through multiple channels:\n\n"
            "- **Certificate Transparency (CT) logs** — Every publicly trusted TLS certificate "
            "is logged; services like crt.sh reveal `api`, `staging`, `jenkins`, and regional "
            "variants.\n"
            "- **Passive DNS and search engines** — Historical resolutions and indexed pages "
            "expose hosts no longer in active use but still routable.\n"
            "- **Brute force and permutation** — Tools combine wordlists (`subdomains-top1million`) "
            "with the root domain and resolve via high-speed resolvers (`massdns`, `puredns`).\n"
            "- **Zone transfers and DNS records** — Misconfigured NS servers may AXFR entire zones.\n\n"
            "**Wildcard DNS** (`*.target.com → single IP`) complicates enumeration: brute-force "
            "hits return false positives unless tools detect wildcard responses and filter them. "
            "Each discovered subdomain may host a distinct application, API, admin panel, or "
            "cloud service with different security posture."
        ),
        "exploitation": (
            "1. **Passive sweep** — `subfinder -d target.com -all -o passive.txt` and "
            "`amass enum -passive -d target.com` before sending any direct DNS traffic.\n"
            "2. **CT log mining** — Query crt.sh for `%.target.com` and deduplicate SAN entries.\n"
            "3. **Brute force with wildcard handling** — `puredns bruteforce wordlist.txt "
            "target.com -r resolvers.txt -w resolved.txt` filters wildcard noise.\n"
            "4. **Permutation scanning** — `gotator` or `alterx` generate `dev-api`, "
            "`api-dev`, `api-staging` variants from known subdomains.\n"
            "5. **Resolve and validate** — `dnsx -l candidates.txt -a -aaaa -cname -resp` "
            "confirms live records and follows CNAME chains to cloud providers.\n"
            "6. **Check for takeovers** — CNAMEs pointing to deprovisioned S3, Azure, GitHub "
            "Pages, or Heroku instances are high-severity findings.\n"
            "7. **Probe each live host** — Pass results to httpx and nuclei; staging subdomains "
            "often lack WAF and auth.\n"
            "8. **Respect scope** — Wildcard `*.target.com` includes all subdomains unless "
            "explicitly excluded in program rules."
        ),
        "defense": (
            "- **Audit all DNS records quarterly**; remove dangling CNAMEs and unused subdomains.\n"
            "- **Disable zone transfers** (AXFR) on authoritative nameservers except to "
            "designated secondaries.\n"
            "- **Avoid wildcard DNS** where possible; if required, return NXDOMAIN for "
            "unprovisioned hosts instead of a catch-all virtual host.\n"
            "- **Use CAA records** and monitor CT logs to detect unauthorized certificate "
            "issuance for your domains.\n"
            "- **Claim or delete** cloud resources referenced by DNS before decommissioning "
            "services (S3, Azure Web Apps, Fastly).\n"
            "- **Segment environments** — Do not point `staging.target.com` at production data; "
            "use separate accounts and credentials.\n"
            "- **Alert on new subdomains** via automated CT monitoring (e.g., Facebook "
            "ct-monitor, Certstream, commercial EASM)."
        ),
    },
    "bug-bounty/asset-discovery": {
        "how_it_works": (
            "Asset discovery goes beyond subdomain lists to build a **complete map of "
            "in-scope resources**: web applications, APIs, mobile backends, cloud storage, "
            "IP ranges, ASN allocations, and third-party integrations.\n\n"
            "Modern organizations expose assets across:\n\n"
            "- **Corporate DNS** — Primary domains and acquired company brands.\n"
            "- **Cloud providers** — S3 buckets, Azure blobs, GCP storage named after the "
            "company (`target-backups`, `target-dev`).\n"
            "- **IP/ASN space** — Netblocks registered to the organization may host services "
            "not linked from public DNS.\n"
            "- **Mobile and desktop apps** — Hardcoded API endpoints, analytics SDKs, and "
            "certificate pinning configs reveal hidden backends.\n"
            "- **Code and artifact leaks** — GitHub, GitLab, npm packages, and Docker Hub "
            "images expose internal hostnames and API keys.\n\n"
            "Attackers correlate these sources to find **forgotten properties**—acquired "
            "startups, deprecated products, and employee side projects still on corporate "
            "infrastructure."
        ),
        "exploitation": (
            "1. **Map ASN and IP ranges** — `asnmap -d target.com` and `mapcidr` to find "
            "netblocks; scan for web services not in DNS.\n"
            "2. **Hunt cloud storage** — Probe `target-dev.s3.amazonaws.com`, permutations "
            "with `cloud_enum`, `s3scanner`, or nuclei S3 templates.\n"
            "3. **Search code repositories** — GitHub dorks: `org:target password`, "
            "`target.com api_key`, `.env target`.\n"
            "4. **Analyze mobile apps** — Decompile APK/IPA with `jadx`; extract API base URLs, "
            "staging hosts, and embedded secrets.\n"
            "5. **Review acquisitions** — Enumerate domains owned by subsidiaries listed in "
            "annual reports or press releases.\n"
            "6. **Crawl for assets** — `katana -u https://target.com -d 5` discovers linked "
            "domains, CDN origins, and third-party widgets.\n"
            "7. **Cross-reference Shodan/Censys** — Search `ssl.cert.subject.cn:target.com` "
            "and `org:\"Target Corp\"` for unlisted services.\n"
            "8. **Validate ownership** — Confirm each asset is in program scope before testing; "
            "document provenance for reports."
        ),
        "defense": (
            "- **Maintain a living asset register** tied to business owners, environment type, "
            "and decommission dates.\n"
            "- **Integrate M&A due diligence** — Transfer or retire DNS, certs, and cloud "
            "accounts when acquiring companies.\n"
            "- **Block public listing** of dev/staging buckets and storage; use private ACLs "
            "and IAM policies by default.\n"
            "- **Scan code repositories** for secrets and internal hostnames; use `gitleaks` "
            "in CI and GitHub Advanced Security.\n"
            "- **Inventory mobile app endpoints** and ensure they route through the same WAF "
            "and auth controls as web.\n"
            "- **Deploy EASM** that correlates DNS, IPs, cloud APIs, and code leaks into one "
            "dashboard.\n"
            "- **Run quarterly \"forgotten asset\" reviews** with security and infrastructure "
            "teams."
        ),
    },
    "bug-bounty/port-scanning": {
        "how_it_works": (
            "Port scanning identifies **open TCP/UDP ports** on target hosts, revealing which "
            "network services accept connections. Each open port maps to a daemon (HTTP/443, "
            "SSH/22, RDP/3389, MySQL/3306) that may contain vulnerabilities or misconfigurations.\n\n"
            "Scanners operate by sending probe packets and analyzing responses:\n\n"
            "- **SYN scan** (`nmap -sS`) — Sends SYN, interprets SYN-ACK as open; stealthier "
            "than full connect.\n"
            "- **Connect scan** — Completes TCP handshake; required without raw socket privileges.\n"
            "- **Mass scanning** — `masscan` and `naabu` scan entire ranges at high speed using "
            "asynchronous I/O.\n\n"
            "In bug bounty, port scanning is usually limited to **in-scope hosts** and may be "
            "restricted by program rules (rate limits, no full 65535-port sweeps). High-value "
            "findings include exposed databases, Redis/Memcached without auth, Docker APIs "
            "(2375), Kubernetes API (6443), and management panels (Jenkins 8080, Tomcat 8080)."
        ),
        "exploitation": (
            "1. **Start with top ports** — `naabu -host target.com -top-ports 1000` or "
            "`nmap --top-ports 1000 target.com` for fast initial coverage.\n"
            "2. **Expand on high-value hosts** — Full port scan (`-p-`) on staging, VPN "
            "gateways, and IPs from ASN mapping.\n"
            "3. **Fingerprint services** — `nmap -sV -sC -p <ports> target.com` for version "
            "detection and default script output.\n"
            "4. **Check UDP selectively** — DNS (53), SNMP (161), and NTP (123) when in scope; "
            "UDP scans are slow but find SNMP community strings.\n"
            "5. **Hunt management interfaces** — Probe 8080, 8443, 9090, 3000, 5601 (Kibana), "
            "9200 (Elasticsearch).\n"
            "6. **Test default credentials** — Exposed Redis, MongoDB, and Elasticsearch often "
            "require no authentication.\n"
            "7. **Respect rate limits** — Use `-T3` or lower; aggressive scanning may trigger "
            "abuse reports or program bans.\n"
            "8. **Document service banners** — Include version strings in reports for CVE "
            "correlation."
        ),
        "defense": (
            "- **Default-deny firewall posture** — Only expose 443 (and 80 for redirect) to "
            "the internet; block all other ports at the perimeter.\n"
            "- **No direct database exposure** — Bind MySQL, PostgreSQL, Redis to localhost "
            "or private subnets; use bastion/VPN for admin access.\n"
            "- **Patch and harden exposed services** — If a port must be public, keep software "
            "current and require strong authentication.\n"
            "- **Use cloud security groups** — Audit rules quarterly; remove `0.0.0.0/0` on "
            "non-HTTP ports.\n"
            "- **Deploy IDS/IPS** to alert on port sweeps and connection attempts to "
            "management ports.\n"
            "- **Segment internal services** — Even if one host is compromised, lateral "
            "scanning should not reach databases.\n"
            "- **Continuous external scanning** — Run internal port scans from outside to "
            "verify perimeter rules hold."
        ),
    },
    "bug-bounty/http-probing": {
        "how_it_works": (
            "HTTP probing determines which discovered hosts serve **live web applications** "
            "and collects metadata for prioritization: HTTP status codes, page titles, redirect "
            "chains, TLS certificates, response sizes, and technology fingerprints.\n\n"
            "A host may resolve in DNS but return no web service; probing filters the asset list "
            "to actionable targets. Probers send HTTP/HTTPS requests (often HEAD or GET) and "
            "parse responses in parallel across thousands of hosts.\n\n"
            "Key signals:\n\n"
            "- **Status codes** — 200 (live app), 401/403 (auth required—interesting), 302 "
            "(redirect chains reveal internal hostnames).\n"
            "- **Titles** — `Login`, `Dashboard`, `phpMyAdmin`, `Index of /` indicate "
            "high-value targets.\n"
            "- **TLS cert SANs** — Certificate subject alternative names reveal additional "
            "hostnames for recursive enumeration.\n"
            "- **CDN/WAF presence** — Cloudflare, Akamai, and AWS CloudFront headers affect "
            "which tests will succeed.\n\n"
            "Tools like `httpx` integrate probing with tech detection, screenshotting, and "
            "favicon hashing for efficient pipeline stages."
        ),
        "exploitation": (
            "1. **Probe all resolved hosts** — `httpx -l hosts.txt -title -status-code "
            "-tech-detect -follow-redirects -threads 50 -o live.txt`.\n"
            "2. **Test both HTTP and HTTPS** — Some apps only respond on one scheme; use "
            "`-ports 80,443,8080,8443`.\n"
            "3. **Capture redirect chains** — `-follow-redirects` reveals `staging.internal` "
            "hostnames in Location headers.\n"
            "4. **Hash favicons** — `httpx -favicon` matches default admin panel icons "
            "(Shodan favicon hash database).\n"
            "5. **Screenshot for triage** — `gowitness` or `aquatone` visualizes hundreds of "
            "hosts for quick manual review.\n"
            "6. **Filter by status** — Prioritize 200/401/403; investigate 502/503 for "
            "backend misconfigurations.\n"
            "7. **Extract TLS SANs** — `httpx -tls-probe -json` feeds new subdomains back "
            "into enumeration.\n"
            "8. **Build target tiers** — Tier 1: login pages and APIs; Tier 2: static sites; "
            "Tier 3: error pages worth content discovery."
        ),
        "defense": (
            "- **Remove or protect unused virtual hosts** — Default nginx/Apache pages on "
            "forgotten vhosts are common low-hanging fruit.\n"
            "- **Normalize redirects** — Avoid leaking internal hostnames in Location headers.\n"
            "- **Require authentication** on staging and admin interfaces; do not rely on "
            "obscurity.\n"
            "- **Deploy WAF/CDN** consistently across all public vhosts, not only the main site.\n"
            "- **Monitor for new live hosts** — Alert when httpx-equivalent scans would find "
            "new 200 responses on your IP space.\n"
            "- **Use consistent TLS certificates** — Minimize SAN sprawl that expands "
            "attacker subdomain lists.\n"
            "- **Return generic error pages** — Avoid verbose server banners and stack traces "
            "on probed endpoints."
        ),
    },
    "bug-bounty/dns-enumeration": {
        "how_it_works": (
            "DNS enumeration extracts the **naming and routing infrastructure** behind a "
            "domain: A/AAAA records (IPs), CNAME aliases (often to CDNs or cloud), MX (mail "
            "servers), NS (authoritative nameservers), TXT (SPF, DKIM, DMARC, domain "
            "verification tokens), and SRV records.\n\n"
            "DNS data reveals:\n\n"
            "- **Mail infrastructure** — MX records expose Microsoft 365, Google Workspace, or "
            "self-hosted Exchange (common phish and auth targets).\n"
            "- **Email security posture** — SPF (`v=spf1`), DKIM selectors, and DMARC "
            "(`p=reject` vs `p=none`) indicate spoofing resistance.\n"
            "- **Third-party integrations** — TXT records for Atlassian, Salesforce, Zoom, "
            "and Stripe verification prove service relationships.\n"
            "- **Zone transfer (AXFR)** — If misconfigured, returns the entire zone in one query.\n"
            "- **Dangling records** — CNAMEs to deleted cloud resources enable subdomain takeover.\n\n"
            "DNS is often overlooked but provides high-impact findings without aggressive scanning."
        ),
        "exploitation": (
            "1. **Query all record types** — `dnsx -d target.com -a -aaaa -cname -mx -ns -txt "
            "-srv -resp` or `dig ANY target.com`.\n"
            "2. **Attempt zone transfer** — `dig axfr @ns1.target.com target.com` against each "
            "listed nameserver.\n"
            "3. **Analyze SPF/DMARC** — `dig txt target.com` and `_dmarc.target.com`; weak "
            "SPF (`+all`, overly broad includes) enables email spoofing reports.\n"
            "4. **Enumerate DKIM selectors** — Common selectors: `default`, `google`, "
            "`selector1`, `k1`.\n"
            "5. **Reverse DNS on discovered IPs** — `dig -x <ip>` reveals shared hosting and "
            "additional hostnames.\n"
            "6. **Hunt dangling CNAMEs** — Resolve CNAME chains; probe for NXDOMAIN, "
            "NoSuchBucket, or GitHub 404 at the target.\n"
            "7. **Search DNS history** — SecurityTrails, ViewDNS, and passive DNS APIs for "
            "removed records still cached.\n"
            "8. **Document takeover proof** — Claim dangling resources only per program rules; "
            "serve a harmless PoC file."
        ),
        "defense": (
            "- **Disable AXFR** to unauthorized clients on all authoritative nameservers.\n"
            "- **Implement strict DMARC** (`p=reject`) after SPF and DKIM alignment testing.\n"
            "- **Tighten SPF** — Use `-all` or `~all`; avoid `+all` and excessive `include:` "
            "directives.\n"
            "- **Remove DNS records** when decommissioning services; automate cleanup in "
            "terraform/CD pipelines.\n"
            "- **Monitor CNAME targets** — Alert when a CNAME points to an unclaimed cloud "
            "resource.\n"
            "- **Use DNSSEC** where supported to prevent cache poisoning (does not stop "
            "enumeration).\n"
            "- **Audit TXT records** for leaked secrets and obsolete verification tokens."
        ),
    },
    "bug-bounty/tech-detection": {
        "how_it_works": (
            "Technology detection fingerprints the **software stack** behind web applications: "
            "web servers (nginx, IIS), frameworks (Django, Rails, Spring), CMS platforms "
            "(WordPress, Drupal), JavaScript libraries, CDNs, WAFs, analytics, and payment "
            "processors.\n\n"
            "Fingerprints come from:\n\n"
            "- **HTTP response headers** — `Server`, `X-Powered-By`, `X-AspNet-Version`.\n"
            "- **HTML patterns** — Meta generator tags, comment blocks, known DOM structures.\n"
            "- **JavaScript and CSS paths** — `/wp-content/`, `/_next/static/`, `bundle.js` hashes.\n"
            "- **Cookies** — `PHPSESSID`, `JSESSIONID`, `laravel_session`.\n"
            "- **TLS certificate fields** — Organization names on internal services.\n"
            "- **Favicon hashes** — Unique icons map to default installs (Jenkins, Grafana).\n\n"
            "Once identified, versions are correlated with **CVE databases** and nuclei "
            "templates for targeted exploitation. Tech detection turns blind fuzzing into "
            "stack-aware testing."
        ),
        "exploitation": (
            "1. **Run automated detection** — `httpx -tech-detect`, `whatweb`, or Wappalyzer "
            "browser extension on each live host.\n"
            "2. **Inspect headers manually** — Burp proxy reveals `Server`, custom `X-*` "
            "headers, and framework cookies.\n"
            "3. **Map JavaScript dependencies** — Review `package.json` leaks, webpack chunks, "
            "and known library versions in source.\n"
            "4. **Identify WAF/CDN** — `wafw00f` or nuclei WAF detection; adjust payloads "
            "for bypass techniques.\n"
            "5. **Correlate versions to CVEs** — Search NVD for detected nginx 1.18, Struts "
            "2.5, or Log4j versions.\n"
            "6. **Run targeted nuclei templates** — `nuclei -t cves/ -tags wordpress` based "
            "on fingerprint.\n"
            "7. **Check for end-of-life software** — PHP 7.4, Python 2.7, Windows Server 2012 "
            "indicate patch gaps.\n"
            "8. **Document stack in reports** — Include version evidence (banner, file path) "
            "for triage teams."
        ),
        "defense": (
            "- **Suppress version banners** — Remove `Server` and `X-Powered-By` headers at "
            "reverse proxies.\n"
            "- **Patch aggressively** — Subscribe to vendor advisories for your exact stack; "
            "test patches in staging first.\n"
            "- **Remove unused plugins and modules** — WordPress plugins and npm dependencies "
            "expand CVE surface.\n"
            "- **Deploy WAF rules** tuned to your framework's common attack patterns.\n"
            "- **Use dependency scanning** — Dependabot, Snyk, and OWASP Dependency-Check "
            "in CI/CD.\n"
            "- **Segment EOL systems** — Isolate unpatchable legacy apps behind VPN until "
            "replaced.\n"
            "- **Inventory third-party scripts** — Analytics and chat widgets introduce "
            "supply-chain risk."
        ),
    },
    "network/active-directory": {
        "how_it_works": (
            "Active Directory (AD) is Microsoft's centralized identity and access management "
            "system for Windows domains. A **domain** contains **users**, **computers**, "
            "**groups**, and **Group Policy Objects (GPOs)** stored on **Domain Controllers "
            "(DCs)**. Authentication uses **Kerberos** (ticket-based) and **NTLM** "
            "(challenge-response); authorization is enforced through **Access Control Lists "
            "(ACLs)** on directory objects.\n\n"
            "Attackers target AD because compromising a domain admin account grants control "
            "over every joined system. Key concepts:\n\n"
            "- **LDAP** — Query users, groups, SPNs, and ACLs.\n"
            "- **Kerberos tickets** — TGT (authentication), TGS (service access).\n"
            "- **Delegation** — Constrained/unconstrained delegation allows impersonation.\n"
            "- **Trust relationships** — Parent/child and forest trusts expand blast radius.\n"
            "- **ACL abuse** — `GenericAll`, `WriteDACL`, `ForceChangePassword` on users or "
            "groups enable privilege escalation paths.\n\n"
            "BloodHound visualizes these relationships as attack graphs from any compromised "
            "principal to Domain Admin."
        ),
        "exploitation": (
            "1. **Gain initial foothold** — Phishing, VPN creds, or vulnerable external service "
            "yields a domain-joined workstation or user account.\n"
            "2. **Enumerate with LDAP** — `PowerView`, `ldapsearch`, or `bloodhound-python` "
            "to list users, groups, computers, and ACLs.\n"
            "3. **Identify quick wins** — AS-REP roastable accounts (no preauth), Kerberoastable "
            "SPNs, GPP passwords in SYSVOL, LLMNR/NBT-NS poisoning via Responder.\n"
            "4. **Crack or relay** — Offline hash cracking (hashcat) or NTLM relay to SMB/LDAP.\n"
            "5. **Map attack paths** — Import BloodHound data; find shortest path to "
            "`Domain Admins` or `Enterprise Admins`.\n"
            "6. **Exploit ACL edges** — `GenericAll` on user → reset password; `WriteOwner` on "
            "group → add self.\n"
            "7. **Escalate to DA** — DCSync, Golden Ticket, or group membership abuse.\n"
            "8. **Document per ROE** — Use `-ldap` safe mode in labs; avoid destructive "
            "changes in production assessments."
        ),
        "defense": (
            "- **Tiered Administration Model** — Separate admin accounts (Tier 0) from daily-use "
            "workstations; never log into Tier 0 systems from Tier 2.\n"
            "- **Enable AES-only Kerberos** and require preauthentication; disable RC4 where "
            "possible.\n"
            "- **Audit and harden ACLs** — Remove excessive `GenericAll`/`WriteDACL` on users, "
            "groups, and OUs; use tools like `BloodHound` defensively.\n"
            "- **Deploy LAPS** for local admin password randomization on workstations.\n"
            "- **Disable LLMNR/NBT-NS** and SMB signing enforcement to block relay attacks.\n"
            "- **Enable Protected Users group** for privileged accounts; enforce MFA for all "
            "admin authentication.\n"
            "- **Monitor** Event ID 4769 (Kerberoasting), 4662 (replication), and 4624 "
            "anomalous logons.\n"
            "- Follow [Microsoft's AD security baseline](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory)."
        ),
    },
    "network/active-directory/kerberoasting": {
        "how_it_works": (
            "Kerberoasting exploits how Kerberos issues **Ticket Granting Service (TGS) "
            "tickets** for accounts with **Service Principal Names (SPNs)**. When a domain user "
            "requests access to a service (e.g., MSSQL, HTTP, CIFS), the DC returns a TGS "
            "ticket encrypted with the **service account's password hash**.\n\n"
            "Any authenticated domain user can request TGS tickets for SPNs they can see in AD. "
            "Because the ticket is encrypted with the service account's credentials, an attacker "
            "can **extract the ciphertext offline** and crack it with hashcat without triggering "
            "account lockout—the attack never guesses passwords against the DC.\n\n"
            "High-value targets: service accounts with weak passwords, accounts with "
            "`GenericAll` on other objects, and SQL/IIS service accounts running as domain users."
        ),
        "exploitation": (
            "1. **Find SPN accounts** — `GetUserSPNs.py domain/user:pass -dc-ip <DC>` or "
            "`Rubeus.exe kerberoast /stats`.\n"
            "2. **Request TGS tickets** — `Rubeus.exe kerberoast /outfile:hashes.txt` or "
            "Impacket `GetUserSPNs -request`.\n"
            "3. **Extract hashes** — Output format `$krb5tgs$23$*` for hashcat mode 13100.\n"
            "4. **Crack offline** — `hashcat -m 13100 hashes.txt rockyou.txt -r rules/best64.rule`.\n"
            "5. **Target AES tickets if available** — Mode 19700 for `$krb5tgs$18$*` (slower "
            "but captures stronger accounts).\n"
            "6. **Validate cracked creds** — `crackmapexec smb <target> -u svc_account -p "
            "password`.\n"
            "7. **Pivot** — Use recovered service account for lateral movement, ACL abuse, or "
            "further Kerberoasting if the account has new SPNs.\n"
            "8. **Report** — Document SPN list, crack time, and downstream access gained."
        ),
        "defense": (
            "- **Use Group Managed Service Accounts (gMSA)** — Automatic 120-character "
            "passwords rotated by AD; not crackable via Kerberoasting.\n"
            "- **Strong service account passwords** — 25+ random characters if gMSA is not "
            "feasible.\n"
            "- **Least privilege on SPN accounts** — Service accounts should not be domain "
            "admins or have excessive ACLs.\n"
            "- **Monitor Event ID 4769** — Alert on unusual TGS requests (many SPNs from one "
            "user, RC4 encryption type 0x17).\n"
            "- **Prefer AES Kerberos encryption** — RC4 (etype 23) tickets are faster to crack.\n"
            "- **Audit SPN registrations** — Remove stale SPNs from decommissioned services.\n"
            "- **Deploy honeypot SPN accounts** — Canary SPNs that alert on any TGS request."
        ),
    },
    "network/bloodhound": {
        "how_it_works": (
            "BloodHound is a graph analysis tool that maps **Active Directory attack paths**. "
            "Collectors (`SharpHound`, `bloodhound.py`) ingest LDAP, session, ACL, GPO, and "
            "trust data into a Neo4j graph database. Nodes represent users, computers, groups, "
            "GPOs, and domains; edges represent relationships like **MemberOf**, **HasSession**, "
            "**GenericAll**, **AdminTo**, and **CanRDP**.\n\n"
            "Pre-built queries find:\n\n"
            "- Shortest path from owned principals to **Domain Admins**.\n"
            "- **Kerberoastable** and **AS-REP roastable** users.\n"
            "- Computers where Domain Users have **local admin**.\n"
            "- **Unconstrained delegation** and **ADCS ESC** misconfigurations (with "
            "SharpHound CE).\n\n"
            "BloodHound turns manual ACL review into visual, queryable attack planning—used "
            "by both red and blue teams."
        ),
        "exploitation": (
            "1. **Collect data** — `SharpHound.exe -c All,GPOLocalGroup` from a domain-joined "
            "host or `bloodhound-python -u user -p pass -d domain -ns <DC>`.\n"
            "2. **Import ZIP** — Upload collector output to BloodHound CE or legacy GUI.\n"
            "3. **Mark owned nodes** — Right-click compromised users/computers as \"Owned\".\n"
            "4. **Run path queries** — \"Shortest Path to Domain Admins from Owned\".\n"
            "5. **Review high-value edges** — `GenericAll`, `WriteDACL`, `ForceChangePassword`, "
            "`AddMember`, `Owns`.\n"
            "6. **Check session data** — `HasSession` edges show where domain admins are logged "
            "in (credential theft targets).\n"
            "7. **Iterate** — After each escalation, re-mark owned and re-query paths.\n"
            "8. **Export for reporting** — Screenshot attack paths for pentest deliverables."
        ),
        "defense": (
            "- **Run BloodHound defensively** — Schedule monthly collections; remediate paths "
            "before attackers find them.\n"
            "- **Break attack paths** — Remove `GenericAll` on users/groups, disable "
            "unnecessary SPNs, enforce tiered admin.\n"
            "- **Limit session exposure** — Admins should use PAW (Privileged Access "
            "Workstations); avoid daily DA logons on workstations.\n"
            "- **Monitor collector activity** — LDAP enumeration from non-admin workstations "
            "may indicate SharpHound execution.\n"
            "- **Harden ADCS** — BloodHound CE ESC queries reveal certificate template "
            "misconfigurations; apply [SpecterOps hardening guidance](https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf).\n"
            "- **Integrate with SIEM** — Alert on mass LDAP queries and unusual SPN enumeration."
        ),
    },
    "network/dcsync": {
        "how_it_works": (
            "DCSync is a technique that abuses the **Directory Replication** protocol (MS-DRSR) "
            "to impersonate a Domain Controller and **replicate password hashes** from a real DC "
            "without running code on it. The attacker requests replication of user objects "
            "(including `unicodePwd` and `ntlmhash` attributes) as if they were a legitimate DC.\n\n"
            "Required rights (any one suffices in practice):\n\n"
            "- `Replicating Directory Changes`\n"
            "- `Replicating Directory Changes All`\n"
            "- Membership in **Domain Admins**, **Enterprise Admins**, or **Administrators** "
            "on the domain root object.\n\n"
            "DCSync dumps **all domain password hashes**, enabling Golden Ticket creation, "
            "Pass-the-Hash across the domain, and offline cracking of every account. It is "
            "stealthier than running Mimikatz on a DC because it uses normal replication traffic."
        ),
        "exploitation": (
            "1. **Obtain replication rights** — Via prior escalation (ACL abuse granting "
            "`Replicating Directory Changes All`) or Domain Admin membership.\n"
            "2. **Run DCSync** — `mimikatz # lsadump::dcsync /domain:corp.local /user:krbtgt` "
            "or `secretsdump.py domain/admin:pass@<DC> -just-dc`.\n"
            "3. **Dump krbtgt hash** — Required for Golden Ticket forgery.\n"
            "4. **Dump all users** — `secretsdump.py` outputs NTLM hashes for offline cracking "
            "or Pass-the-Hash.\n"
            "5. **Avoid DC execution** — DCSync runs from any machine with rights; no need to "
            "compromise the DC itself.\n"
            "6. **Golden Ticket** — Use krbtgt hash to forge TGTs for any user indefinitely "
            "(until krbtgt password is rotated twice).\n"
            "7. **Handle evidence carefully** — Per engagement ROE; hashes are crown-jewel data.\n"
            "8. **Report remediation** — Identify which ACL edge granted replication rights."
        ),
        "defense": (
            "- **Restrict replication rights** — Only Domain Controllers should hold "
            "`Replicating Directory Changes All`; audit ACLs on domain root.\n"
            "- **Monitor Event ID 4662** — Operations with properties `1131f6aa-9c07-11d1-f79f-00c04fc2dcd2` "
            "(DS-Replication-Get-Changes-All) from non-DC sources.\n"
            "- **Tier 0 isolation** — Limit Domain Admin membership; use JIT/JEA for admin tasks.\n"
            "- **Rotate krbtgt twice** after compromise — Required to invalidate Golden Tickets.\n"
            "- **Deploy Microsoft Defender for Identity** — Detects DCSync anomalies.\n"
            "- **Use Protected Users** for admin accounts — Prevents NTLM and unconstrained "
            "delegation abuse.\n"
            "- **Regular BloodHound ACL audits** — Find and remove unintended replication rights."
        ),
    },
    "network/pentesting": {
        "how_it_works": (
            "Network penetration testing simulates real-world attackers against **internal and "
            "external network infrastructure** within defined scope and rules of engagement "
            "(ROE). The methodology follows PTES (Penetration Testing Execution Standard) phases:\n\n"
            "1. **Pre-engagement** — Scope subnets, critical assets, excluded systems, and "
            "emergency contacts.\n"
            "2. **Intelligence gathering** — OSINT, DNS, and passive recon on external ranges.\n"
            "3. **Threat modeling** — Identify high-value targets (DCs, databases, payment systems).\n"
            "4. **Vulnerability analysis** — Port scans, vulnerability scans, and manual review.\n"
            "5. **Exploitation** — Gain foothold, escalate, and pivot per ROE.\n"
            "6. **Post-exploitation** — Demonstrate impact (data access, domain compromise).\n"
            "7. **Reporting** — Risk-ranked findings with reproduction steps and remediation.\n\n"
            "External tests start from the internet; internal tests simulate insider or "
            "breached-perimeter scenarios from a corporate VLAN or VPN."
        ),
        "exploitation": (
            "1. **External recon** — Map in-scope IPs/ASNs; `nmap`, `masscan`, and service "
            "enumeration on perimeter.\n"
            "2. **Initial access** — Exploit vulnerable services (VPN, Exchange, Citrix), "
            "phishing, or credential stuffing.\n"
            "3. **Internal enumeration** — `crackmapexec`, `enum4linux-ng`, LLMNR poisoning, "
            "and BloodHound collection.\n"
            "4. **Vulnerability exploitation** — Target unpatched SMB, RDP, and web apps on "
            "internal hosts.\n"
            "5. **Credential harvesting** — Mimikatz, LSASS dumps, Kerberoasting, and GPP "
            "passwords.\n"
            "6. **Lateral movement** — Pass-the-Hash, WinRM, PsExec to reach critical segments.\n"
            "7. **Objective completion** — Access domain admin, sensitive database, or crown "
            "jewel per scope.\n"
            "8. **Maintain OPSEC** — Document all actions; avoid production outages and data "
            "exfiltration beyond proof."
        ),
        "defense": (
            "- **Defense in depth** — Perimeter firewalls, segmentation, EDR, and SIEM "
            "correlation.\n"
            "- **Patch management** — Prioritize internet-facing and critical internal systems.\n"
            "- **Network segmentation** — VLANs, micro-segmentation, and zero-trust policies "
            "limit lateral movement.\n"
            "- **Credential hygiene** — MFA everywhere, LAPS, no shared admin passwords.\n"
            "- **Regular pentests** — Annual external + internal; retest remediated findings.\n"
            "- **Purple team exercises** — Validate detections against ATT&CK techniques.\n"
            "- **Incident response readiness** — Playbooks for containment when pentest-like "
            "activity is detected."
        ),
    },
    "network/privilege-escalation/windows": {
        "how_it_works": (
            "Windows privilege escalation elevates access from a **low-privilege user** to "
            "**LOCAL SYSTEM** or **Administrator** on a host. Common vectors:\n\n"
            "- **Misconfigured services** — Unquoted service paths, weak service binary "
            "permissions, modifiable service DLLs.\n"
            "- **Registry and scheduled tasks** — Writable `AutoRun` keys, tasks running as SYSTEM.\n"
            "- **Token impersonation** — `SeImpersonatePrivilege` (PrintSpoofer, Juicy Potato) "
            "on service accounts.\n"
            "- **Credential storage** — Saved RDP creds, WiFi passwords, browser vaults, DPAPI.\n"
            "- **Kernel exploits** — Unpatched CVEs when patching is behind.\n"
            "- **AlwaysInstallElevated** — MSI installs run as SYSTEM.\n\n"
            "Post-exploitation enumeration (`winPEAS`, `PowerUp`) automates checking hundreds "
            "of misconfiguration patterns."
        ),
        "exploitation": (
            "1. **Enumerate** — `winPEAS.exe`, `seatbelt.exe system`, or manual `whoami /priv`.\n"
            "2. **Check service misconfigs** — `accesschk.exe` on service binaries and "
            "unquoted paths (`wmic service get pathname`).\n"
            "3. **Exploit SeImpersonate** — `PrintSpoofer.exe -i -c cmd` or `GodPotato` on "
            "Windows Server 2019+.\n"
            "4. **Writable directories** — Replace DLLs in PATH or service folders.\n"
            "5. **Scheduled tasks** — `schtasks` listing; modify scripts run as SYSTEM.\n"
            "6. **Stored credentials** — `cmdkey /list`, `mimikatz vault::list`.\n"
            "7. **Kernel exploits** — Last resort; `systeminfo` for patch level vs exploit-db.\n"
            "8. **Document** — Capture `whoami` before/after; note exact misconfiguration."
        ),
        "defense": (
            "- **Apply CIS Windows benchmarks** — Harden service permissions, UAC, and "
            "PowerShell logging.\n"
            "- **Quote all service paths** and set restrictive ACLs on service binaries.\n"
            "- **Disable SeImpersonate** for service accounts that do not require it.\n"
            "- **Patch aggressively** — Automate WSUS/Intune patching; prioritize critical CVEs.\n"
            "- **Remove local admin rights** from standard users.\n"
            "- **Enable Credential Guard** and LSA protection on supported Windows versions.\n"
            "- **Deploy EDR** with tamper protection; alert on Mimikatz, Potato exploits, and "
            "suspicious service modifications."
        ),
    },
    "network/privilege-escalation/linux": {
        "how_it_works": (
            "Linux privilege escalation gains **root** from an unprivileged shell. Attack "
            "surface includes:\n\n"
            "- **SUID/SGID binaries** — Programs running with elevated privileges (find, vim, "
            "custom apps with command injection).\n"
            "- **Sudo misconfigurations** — `(ALL) NOPASSWD: ALL` or exploitable allowed "
            "commands (`sudo vim`, `sudo find`).\n"
            "- **Cron jobs** — World-writable scripts executed as root.\n"
            "- **Capabilities** — `cap_setuid` on binaries like `python3`.\n"
            "- **Kernel exploits** — Dirty COW, PwnKit, OverlayFS when unpatched.\n"
            "- **Container escapes** — Docker socket (`/var/run/docker.sock`), privileged "
            "containers, mounted host paths.\n"
            "- **Secrets in files** — `.bash_history`, config files, SSH keys, `/etc/shadow` "
            "if readable.\n\n"
            "`linpeas.sh` automates enumeration across these categories."
        ),
        "exploitation": (
            "1. **Run linpeas** — `curl -L linpeas.sh | sh` or upload and execute offline.\n"
            "2. **Check sudo** — `sudo -l` for NOPASSWD entries; GTFOBins for exploit paths.\n"
            "3. **Find SUID** — `find / -perm -4000 2>/dev/null`; cross-reference GTFOBins.\n"
            "4. **Review cron** — `cat /etc/crontab`, `/etc/cron.d/`, user crontabs.\n"
            "5. **Capabilities** — `getcap -r / 2>/dev/null`.\n"
            "6. **Writable /etc/passwd** — Add root user with known password hash.\n"
            "7. **Container escape** — If in Docker, check `docker.sock`, `--privileged`, "
            "host mounts; use `cdk` or `deepce`.\n"
            "8. **Kernel exploit** — `uname -a` vs exploit-db; lab-only unless explicitly in scope."
        ),
        "defense": (
            "- **Minimize SUID binaries** — Remove unnecessary setuid; audit with `find / -perm "
            "-4000`.\n"
            "- **Restrict sudo** — Explicit command lists; no NOPASSWD for shells or editors.\n"
            "- **Secure cron** — Root-only writable cron directories; validate script permissions.\n"
            "- **Patch kernels** — Automated unattended-upgrades; monitor CVE feeds.\n"
            "- **Harden containers** — Non-root users, drop capabilities, read-only rootfs, no "
            "docker.sock mounts.\n"
            "- **AppArmor/SELinux** — Enforce mandatory access controls.\n"
            "- **Audit logging** — `auditd` rules for privilege changes and sudo usage."
        ),
    },
    "network/lateral-movement": {
        "how_it_works": (
            "Lateral movement is the technique of **expanding access** from one compromised "
            "host to others within a network using harvested credentials, tokens, and trust "
            "relationships. Unlike privilege escalation (local root/admin), lateral movement "
            "operates **across systems**.\n\n"
            "Common protocols and methods:\n\n"
            "- **Pass-the-Hash (PtH)** — NTLM hash authentication without plaintext password.\n"
            "- **Pass-the-Ticket (PtT)** — Reuse Kerberos TGT/TGS tickets.\n"
            "- **SMB/WMI/WinRM** — Remote command execution with valid creds.\n"
            "- **RDP** — Interactive desktop access.\n"
            "- **SSH** — Key reuse and agent forwarding on Linux.\n"
            "- **DCOM** — Remote instantiation of COM objects.\n\n"
            "Domain environments amplify lateral movement: shared local admin passwords, "
            "excessive group memberships, and cached credentials on workstations."
        ),
        "exploitation": (
            "1. **Harvest credentials** — Mimikatz, LSASS dumps, Kerberoasting, and "
            "credential manager on foothold host.\n"
            "2. **Identify targets** — BloodHound `HasSession`, `AdminTo`, and `CanRDP` edges.\n"
            "3. **Spray or PtH** — `crackmapexec smb 10.0.0.0/24 -u admin -H <NTLM> --local-auth`.\n"
            "4. **WinRM access** — `evil-winrm -i <host> -u user -p pass` for PowerShell remoting.\n"
            "5. **PSExec/WMI** — `impacket-psexec` or `wmiexec.py` for semi-interactive shells.\n"
            "6. **Pass-the-Ticket** — `mimikatz kerberos::ptt` with exported .kirbi files.\n"
            "7. **SSH key reuse** — Copy `id_rsa` from `~/.ssh` to pivot to Linux servers.\n"
            "8. **Maintain OPSEC** — Use `-session` logging; avoid noisy mass scans in production."
        ),
        "defense": (
            "- **Disable NTLM** where possible; enforce Kerberos with AES and EPA.\n"
            "- **Enable SMB signing** and LDAP signing/channel binding.\n"
            "- **LAPS and unique local admin passwords** — Block PtH across workstations.\n"
            "- **Restrict WinRM/RDP** — Allow only from jump hosts/PAM solutions.\n"
            "- **Credential Guard and Protected Users** — Limit hash/ticket extraction.\n"
            "- **Network segmentation** — Firewall rules between VLANs; assume breach design.\n"
            "- **Monitor** — Event 4624 type 3 (network logon), 4648 (explicit creds), and "
            "anomalous SMB/WinRM from workstations."
        ),
    },
    "network/wireless": {
        "how_it_works": (
            "Wireless security assessment evaluates **Wi-Fi networks** (802.11) for encryption "
            "weaknesses, authentication bypass, and segmentation failures. Networks operate in "
            "**managed mode** (clients connect to access points) or **ad hoc**.\n\n"
            "Security modes:\n\n"
            "- **Open** — No encryption; captive portals only.\n"
            "- **WPA2-Personal (PSK)** — Pre-shared key; vulnerable to offline dictionary "
            "attack after 4-way handshake capture.\n"
            "- **WPA2/WPA3-Enterprise (802.1X)** — Per-user certificates or credentials via "
            "RADIUS; misconfigs include weak EAP methods (LEAP, PEAP without cert validation).\n"
            "- **WPA3** — SAE (Dragonfly) resists offline attacks; transition mode may downgrade.\n\n"
            "Assessments also cover **rogue AP detection**, guest network isolation, and "
            "evil-twin resistance."
        ),
        "exploitation": (
            "1. **Survey with monitor mode** — `airmon-ng start wlan0`; `airodump-ng wlan0mon` "
            "to list SSIDs, channels, and clients.\n"
            "2. **Capture handshake** — Deauth clients (`aireplay-ng -0`) to force reconnect "
            "and capture WPA2 4-way handshake.\n"
            "3. **Crack PSK** — `aircrack-ng -w wordlist.txt capture.cap` or `hashcat -m 22000`.\n"
            "4. **Test enterprise EAP** — `eaphammer` or `hostapd-wpe` for credential capture "
            "on rogue APs (authorized assessments only).\n"
            "5. **Evil twin** — Clone corporate SSID; test if clients auto-connect without "
            "certificate pinning.\n"
            "6. **Guest network isolation** — Connect to guest WiFi; attempt to reach internal "
            "RFC1918 ranges.\n"
            "7. **WPS attacks** — `reaver` against WPS-enabled routers (if in scope).\n"
            "8. **Document** — Signal strength, encryption type, and segmentation test results."
        ),
        "defense": (
            "- **Use WPA3 or WPA2-Enterprise** with certificate-based EAP-TLS.\n"
            "- **Strong PSKs** — 20+ random characters if PSK is required; rotate periodically.\n"
            "- **Disable WPS and legacy WEP/WPA**.\n"
            "- **Isolate guest networks** — VLAN segmentation; no route to corporate subnets.\n"
            "- **Deploy WIDS/WIPS** — Detect rogue APs and deauth attacks.\n"
            "- **Certificate pinning for 802.1X** — Prevent evil-twin credential capture.\n"
            "- **Monitor** — Alert on duplicate SSIDs and anomalous AP MAC addresses."
        ),
    },
    "network/firewall-segmentation": {
        "how_it_works": (
            "Firewall and network segmentation testing validates that **security zones** are "
            "properly isolated and that firewall rules enforce least-privilege access. "
            "Organizations define zones such as:\n\n"
            "- **DMZ** — Public-facing web servers.\n"
            "- **Internal/Corporate** — Workstations and general servers.\n"
            "- **Restricted/PCI** — Payment systems, databases, domain controllers.\n"
            "- **Management** — Jump hosts, backup systems, monitoring.\n\n"
            "Testing maps **allowed paths** between zones by probing from compromised or "
            "test hosts in each segment. Common failures: overly permissive egress (`any:any` "
            "outbound), flat networks without VLANs, and \"temporary\" rules never removed."
        ),
        "exploitation": (
            "1. **Document zone map** — Obtain network diagram and rule sets from client (or "
            "infer from traceroute and ARP).\n"
            "2. **Baseline from each zone** — Place test hosts in DMZ, corp, and guest VLANs.\n"
            "3. **Probe cross-zone** — `nmap` and `hping3` to targets in other segments; record "
            "allowed ports.\n"
            "4. **Test egress filtering** — Attempt outbound connections to internet, DNS "
            "tunneling, and C2 ports from internal hosts.\n"
            "5. **Verify DMZ isolation** — From DMZ host, attempt direct access to database "
            "and DC subnets.\n"
            "6. **Check dual-homed hosts** — Systems spanning zones become pivot points.\n"
            "7. **Review rule sprawl** — Compare documented policy vs actual `iptables`/`pf`/"
            "Palo Alto configs.\n"
            "8. **Report gaps** — Rank findings by data sensitivity of reachable assets."
        ),
        "defense": (
            "- **Default-deny** firewall policies between all zones.\n"
            "- **Micro-segmentation** — Workload-level policies (NSX, Illumio) beyond VLANs.\n"
            "- **Quarterly rule reviews** — Remove stale permits; document business justification.\n"
            "- **Restrict egress** — Allow only required destinations; block direct internet "
            "from servers.\n"
            "- **Separate management plane** — Admin access only via PAM/jump hosts.\n"
            "- **Log and alert** — Deny-rule hits may indicate lateral movement attempts.\n"
            "- **Validate with continuous testing** — Internal scanners that verify segmentation "
            "after every change."
        ),
    },
    "cloud/aws": {
        "how_it_works": (
            "Amazon Web Services (AWS) security testing evaluates **Identity and Access "
            "Management (IAM)**, resource misconfigurations, and network exposure across "
            "accounts and regions. Core services under review:\n\n"
            "- **IAM** — Users, roles, policies; privilege escalation via `iam:PassRole`, "
            "`sts:AssumeRole`, and overly permissive `*` actions.\n"
            "- **S3** — Bucket policies and ACLs; public read/write buckets are top findings.\n"
            "- **EC2** — Security groups with `0.0.0.0/0` on SSH/RDP; IMDSv1 SSRF to "
            "instance metadata credentials.\n"
            "- **Lambda/API Gateway** — Overprivileged execution roles and unauthenticated APIs.\n"
            "- **RDS/Secrets Manager** — Publicly accessible databases and hardcoded keys.\n\n"
            "Attackers chain **credential leaks** (git, SSRF) to IAM roles, then enumerate "
            "and escalate within the account using tools like Pacu and Prowler."
        ),
        "exploitation": (
            "1. **Enumerate with leaked creds** — `aws sts get-caller-identity`; `aws iam "
            "list-users` and `list-attached-user-policies`.\n"
            "2. **Run Prowler/ScoutSuite** — Automated misconfiguration scan across services.\n"
            "3. **Hunt public S3** — `aws s3 ls`, nuclei S3 templates, and bucket "
            "name permutations.\n"
            "4. **Test SSRF to IMDS** — From app SSRF, request `http://169.254.169.254/"
            "latest/meta-data/iam/security-credentials/` (IMDSv2 requires token header).\n"
            "5. **Privilege escalation paths** — Pacu modules for `iam:CreateAccessKey`, "
            "`lambda:UpdateFunctionCode`, and `ec2:RunInstances` with admin instance profile.\n"
            "6. **Security group audit** — `0.0.0.0/0` on ports 22, 3389, 3306, 6379.\n"
            "7. **Cross-account roles** — Assume roles with external trust policies.\n"
            "8. **Document per account/region** — Findings must map to resource ARNs."
        ),
        "defense": (
            "- **Enable AWS Organizations SCPs** — Guardrails against public S3 and "
            "unauthorized regions.\n"
            "- **Require IMDSv2** on all EC2 instances; block SSRF metadata theft.\n"
            "- **Least-privilege IAM** — No `*` actions; use permission boundaries and "
            "IAM Access Analyzer.\n"
            "- **S3 Block Public Access** at account level; enable default encryption.\n"
            "- **Enable CloudTrail** in all regions; ship to immutable S3 + SIEM.\n"
            "- **MFA for console** and short-lived credentials via IAM Identity Center.\n"
            "- **Regular Prowler/Config** compliance scans; remediate before external testers."
        ),
    },
    "cloud/azure": {
        "how_it_works": (
            "Microsoft Azure security spans **Azure Active Directory (Entra ID)**, "
            "subscriptions, resource groups, and platform services. Key attack surfaces:\n\n"
            "- **Entra ID** — User enumeration, password spray, OAuth consent phishing, "
            "misconfigured app registrations with excessive API permissions.\n"
            "- **Storage accounts** — Public blob containers and shared access signatures "
            "(SAS) with long expiry.\n"
            "- **Virtual machines** — NSG rules exposing RDP/SSH; managed identities with "
            "broad RBAC.\n"
            "- **Key Vault** — Access policies granting secrets to overprivileged principals.\n"
            "- **Azure DevOps / GitHub** — Pipeline secrets and service connections.\n\n"
            "Azure uses **RBAC** (Owner, Contributor, Reader) at subscription/resource scope. "
            "Managed identities allow VMs and functions to authenticate without stored keys—"
            "but over-assigned roles create lateral movement paths."
        ),
        "exploitation": (
            "1. **Enumerate Entra ID** — `ROADtools` or `azurehound` for users, groups, apps, "
            "and role assignments.\n"
            "2. **Password spray** — `MSOLSpray` or `o365creeper` against synced accounts "
            "(authorized only).\n"
            "3. **Hunt storage exposure** — `MicroBurst` `Get-AzureBlobContent` and public "
            "container scanners.\n"
            "4. **Abuse managed identities** — From compromised VM, request tokens from "
            "`http://169.254.169.254/metadata/identity/oauth2/token`.\n"
            "5. **App registration abuse** — Excessive `Microsoft Graph` permissions "
            "(`Directory.ReadWrite.All`).\n"
            "6. **Conditional access bypass** — Legacy auth protocols, device code flow.\n"
            "7. **Key Vault access** — `az keyvault secret list` with compromised Contributor role.\n"
            "8. **Map to MITRE** — Document Entra vs Azure Resource Manager attack paths."
        ),
        "defense": (
            "- **Enforce Conditional Access** — MFA, compliant devices, block legacy auth.\n"
            "- **Disable public blob access** on storage accounts by default.\n"
            "- **Use Privileged Identity Management (PIM)** — Just-in-time admin roles.\n"
            "- **Audit app registrations** — Restrict admin consent; review API permissions.\n"
            "- **Enable Defender for Cloud** and Entra ID Protection.\n"
            "- **NSG default deny** — No RDP/SSH from internet; use Bastion or VPN.\n"
            "- **Log Analytics** — Centralize Activity Log, Sign-in logs, and Sentinel analytics."
        ),
    },
    "cloud/gcp": {
        "how_it_works": (
            "Google Cloud Platform (GCP) organizes resources in a hierarchy: "
            "**Organization → Folders → Projects**. IAM bindings attach roles to principals "
            "at any level with inheritance.\n\n"
            "Critical services and risks:\n\n"
            "- **Compute Engine** — Firewall rules tagged `0.0.0.0/0`; metadata server at "
            "`169.254.169.254` (similar SSRF risk to AWS).\n"
            "- **Cloud Storage (GCS)** — `allUsers` or `allAuthenticatedUsers` IAM bindings.\n"
            "- **Service accounts** — JSON key leaks; keys do not expire by default.\n"
            "- **GKE (Kubernetes)** — Cluster admin bindings, workload identity misconfigs.\n"
            "- **Cloud Functions** — Overprivileged runtime service accounts.\n\n"
            "GCP's **Organization Policy Service** can enforce constraints (no public IPs, "
            "require OS Login) but is often not fully deployed."
        ),
        "exploitation": (
            "1. **Authenticate** — `gcloud auth activate-service-account` with leaked JSON key "
            "or metadata token from compromised VM.\n"
            "2. **Enumerate IAM** — `gcloud projects get-iam-policy <project>`; hunt "
            "`roles/owner` and `roles/editor`.\n"
            "3. **Scan storage** — `gsutil ls -p <project>`; check `allUsers:objectViewer`.\n"
            "4. **Test SSRF to metadata** — Request metadata with `Metadata-Flavor: Google` header.\n"
            "5. **Service account impersonation** — `roles/iam.serviceAccountTokenCreator` "
            "allows token minting.\n"
            "6. **Firewall audit** — `gcloud compute firewall-rules list` for open SSH/RDP.\n"
            "7. **GKE access** — `kubectl` with exposed endpoints or stolen kubeconfig.\n"
            "8. **Privilege escalation** — `iam.serviceAccounts.setIamPolicy` to grant self "
            "access to powerful SAs."
        ),
        "defense": (
            "- **Disable service account key creation** org policy; use Workload Identity.\n"
            "- **No `allUsers` on buckets** — Use uniform bucket-level access and IAM Conditions.\n"
            "- **VPC Service Controls** — Perimeter around sensitive projects.\n"
            "- **OS Login** for SSH instead of metadata-propagated SSH keys.\n"
            "- **Enable Security Command Center** and audit logs to BigQuery/SIEM.\n"
            "- **Least-privilege IAM** — Custom roles; avoid primitive Owner/Editor.\n"
            "- **Regular Forseti/Scout Suite** assessments."
        ),
    },
    "cloud/kubernetes": {
        "how_it_works": (
            "Kubernetes orchestrates containerized workloads across clusters of nodes. "
            "Security boundaries include:\n\n"
            "- **API server** — Authenticates and authorizes all cluster operations via "
            "RBAC, admission controllers, and optional OPA/Gatekeeper policies.\n"
            "- **etcd** — Stores all cluster state including Secrets (base64, not encrypted "
            "by default).\n"
            "- **Nodes** — Run kubelet, container runtime; compromise grants access to all "
            "pods on the node.\n"
            "- **Pods** — Service accounts with projected tokens; privileged pods can escape "
            "to the host.\n"
            "- **Network policies** — Optional L3/L4 firewall between pods (often not deployed).\n\n"
            "Common misconfigs: anonymous API access, cluster-admin bindings to default "
            "service accounts, secrets mounted in env vars, and exposed Dashboard/etcd."
        ),
        "exploitation": (
            "1. **Enumerate RBAC** — `kubectl auth can-i --list`; `kubectl get "
            "clusterrolebindings -o wide`.\n"
            "2. **Hunt secrets** — `kubectl get secrets -A`; decode base64 values.\n"
            "3. **Privileged pods** — `kubectl run pwn --image=alpine --privileged "
            "--overrides='...hostPID:true'` for node escape.\n"
            "4. **Service account token abuse** — Steal mounted tokens; test permissions "
            "with `kubectl --token=`.\n"
            "5. **kube-hunter/kube-bench** — Scan for exposed API, dashboard, and CIS "
            "benchmark failures.\n"
            "6. **etcd exposure** — Port 2379 without TLS/auth dumps entire cluster state.\n"
            "7. **Supply chain** — Malicious images in registries without admission scanning.\n"
            "8. **Document namespace scope** — Findings per namespace and ClusterRole impact."
        ),
        "defense": (
            "- **Enable RBAC** — No anonymous access; audit cluster-admin bindings.\n"
            "- **Pod Security Standards** (restricted) — No privileged, host namespaces, or "
            "root users.\n"
            "- **Network policies** — Default deny inter-namespace traffic.\n"
            "- **Encrypt etcd at rest**; restrict etcd to control plane only.\n"
            "- **Rotate service account tokens**; use bound tokens with short TTL.\n"
            "- **Admission controllers** — OPA/Gatekeeper, Kyverno for policy enforcement.\n"
            "- **Image scanning** — Trivy/Grype in CI; sign with cosign.\n"
            "- Follow [OWASP Kubernetes Top 10](https://owasp.org/www-project-kubernetes-top-ten/)."
        ),
    },
    "blue-team/detection-engineering": {
        "how_it_works": (
            "Detection engineering is the discipline of building **reliable, actionable "
            "security detections** mapped to adversary behaviors (MITRE ATT&CK). The lifecycle:\n\n"
            "1. **Threat prioritization** — Select techniques relevant to your industry and "
            "threat intel (ransomware, APT, insider threat).\n"
            "2. **Data source identification** — Determine which logs are required (Sysmon, "
            "EDR, Windows Security, DNS, proxy, cloud audit).\n"
            "3. **Detection authoring** — Write Sigma rules, Splunk SPL, KQL, or Elastic "
            "EQL queries with clear logic.\n"
            "4. **Validation** — Execute atomic red team tests or purple team exercises to "
            "confirm true positives.\n"
            "5. **Tuning** — Reduce false positives without blinding to true attacks.\n"
            "6. **Maintenance** — Update rules when log formats, tools, or TTPs change.\n\n"
            "Good detections specify **analytic story**: data source, logic, false positive "
            "guidance, and response playbook link."
        ),
        "exploitation": (
            "1. **Map coverage gaps** — Compare current detections to ATT&CK matrix; prioritize "
            "uncovered techniques with high threat relevance.\n"
            "2. **Author Sigma rules** — Start from [SigmaHQ](https://github.com/SigmaHQ/sigma); "
            "customize for your environment.\n"
            "3. **Convert to SIEM** — Use sigma-cli or Uncoder to generate Splunk/Elastic/Sentinel "
            "queries.\n"
            "4. **Validate with Atomic Red Team** — `Invoke-AtomicTest T1003.001` and confirm "
            "alert fires within SLA.\n"
            "5. **Define severity and MITRE tags** — Every rule links to technique ID and "
            "recommended response.\n"
            "6. **Build detection-as-code** — Store rules in Git; PR review for logic changes.\n"
            "7. **Measure MTTD** — Track time from attack simulation to alert in SOC dashboard.\n"
            "8. **Iterate on false positives** — Add exclusions for known-good admin tools "
            "with change control."
        ),
        "defense": (
            "- **Establish detection engineering as a dedicated function** — Not ad-hoc "
            "analyst queries.\n"
            "- **Maintain ATT&CK coverage dashboard** — Executive visibility into gaps.\n"
            "- **Require validation before production** — No rule goes live without atomic test "
            "evidence.\n"
            "- **Version-control all detections** — Git repo with CI conversion to SIEM formats.\n"
            "- **Quarterly purple team** — Red executes; blue validates and improves detections.\n"
            "- **Document runbooks** — Each high-severity detection links to IR playbook.\n"
            "- **Retire noisy rules** — Failed detections erode SOC trust; fix or remove."
        ),
    },
    "blue-team/siem-log-analysis": {
        "how_it_works": (
            "Security Information and Event Management (SIEM) platforms **aggregate, normalize, "
            "and correlate** logs from across the enterprise for detection and investigation. "
            "Core capabilities:\n\n"
            "- **Log ingestion** — Agents, syslog, API collectors (CloudTrail, Azure Activity, "
            "O365 Management API).\n"
            "- **Parsing and CIM** — Field extraction for consistent searching (`src_ip`, "
            "`user`, `action`).\n"
            "- **Correlation rules** — Join events across sources (failed logon + success from "
            "new geo).\n"
            "- **Search and dashboards** — Ad-hoc investigation and KPI monitoring.\n"
            "- **Retention and compliance** — Hot/warm/cold tiers per regulatory requirements.\n\n"
            "Effective analysis requires understanding **what each log source actually "
            "records** and its blind spots (e.g., PowerShell Script Block Logging off = no "
            "script content)."
        ),
        "exploitation": (
            "1. **Inventory log sources** — Document every onboarded source, parser version, "
            "and field mapping.\n"
            "2. **Build correlation searches** — Example: 10+ failed 4625 followed by 4624 "
            "success (password spray).\n"
            "3. **Create triage dashboards** — Top failed logons, new admin group members, "
            "rare process executions.\n"
            "4. **Develop investigation playbooks** — \"Suspicious logon\" → query VPN, EDR, "
            "proxy for same user/IP.\n"
            "5. **Hunt with baselines** — Compare this week's DNS queries to 30-day average; "
            "flag new domains.\n"
            "6. **Use time normalization** — UTC everywhere; account for clock skew in "
            "correlation windows.\n"
            "7. **Chain across clouds** — Correlate AWS CloudTrail `AssumeRole` with on-prem "
            "VPN logon.\n"
            "8. **Measure ingestion health** — Alert on log source silence (possible "
            "attacker tampering)."
        ),
        "defense": (
            "- **Centralize all critical sources** — EDR, firewall, proxy, DNS, auth, cloud "
            "audit; no silos.\n"
            "- **Enable advanced logging** — Sysmon, PowerShell transcription, command-line "
            "auditing, DNS debug (where appropriate).\n"
            "- **Immutable log storage** — WORM/S3 Object Lock for compliance and anti-tamper.\n"
            "- **Staff SOC analysts** on query languages (SPL, KQL, Lucene) with regular training.\n"
            "- **Monitor ingestion pipeline** — Parser failures silently drop fields.\n"
            "- **Right-size retention** — Balance cost vs investigation window (90+ days "
            "recommended).\n"
            "- **Automate enrichment** — Threat intel feeds, GeoIP, and asset context on every alert."
        ),
    },
    "blue-team/threat-hunting": {
        "how_it_works": (
            "Threat hunting is **proactive, hypothesis-driven search** for adversary activity "
            "that evades automated detections. Unlike alert-driven SOC work, hunters start with "
            "questions:\n\n"
            "- \"Is an attacker using valid credentials for lateral movement?\"\n"
            "- \"Are there signs of Kerberoasting in our domain?\"\n"
            "- \"Did any workstation beacon to a newly registered domain?\"\n\n"
            "The hunting loop:\n\n"
            "1. **Hypothesis** — From threat intel, incident trends, or ATT&CK gaps.\n"
            "2. **Investigation** — Query SIEM, EDR, DNS, and network telemetry.\n"
            "3. **Pattern discovery** — Identify TTPs, IoCs, or behavioral anomalies.\n"
            "4. **Enrichment** — Determine true positive vs benign admin activity.\n"
            "5. **Outcome** — New detection rule, incident escalation, or hypothesis retired.\n\n"
            "Hunting requires curated data, skilled analysts, and executive support for "
            "time not spent on tickets."
        ),
        "exploitation": (
            "1. **Select hypothesis** — Example: \"APT uses WMI for lateral movement\" → "
            "hunt Event 4688 with `wmiprvse.exe` parent processes.\n"
            "2. **Gather data** — Pull 30 days of relevant logs into hunting workspace "
            "(Velociraptor, Jupyter + pandas, or SIEM).\n"
            "3. **Stack counting** — Rare process paths, rare parent-child pairs, rare "
            "command-line arguments.\n"
            "4. **Beaconing analysis** — Periodic HTTPS connections with low jitter to "
            "unknown domains.\n"
            "5. **Credential anomaly** — Logons from new countries, impossible travel, "
            "service account interactive logons.\n"
            "6. **Memory and disk hunts** — YARA scans across endpoints for known implants.\n"
            "7. **Document hunt** — Hypothesis, queries, findings, and detection gaps filled.\n"
            "8. **Convert wins to detections** — Successful hunts become Sigma rules with "
            "tuned thresholds."
        ),
        "defense": (
            "- **Dedicate hunting hours** — Weekly rotation for Tier 2+ analysts.\n"
            "- **Maintain hunt library** — Reusable queries tagged by ATT&CK technique.\n"
            "- **Invest in endpoint visibility** — EDR with process, network, and file telemetry.\n"
            "- **Feed hunts from intel** — ISAC reports, CISA advisories, and internal incident "
            "lessons learned.\n"
            "- **Measure outcomes** — Hunts resulting in new detections or confirmed incidents.\n"
            "- **Purple team integration** — Red validates that hunts would catch simulated TTPs.\n"
            "- **Avoid alert fatigue** — Hunts explore quietly; only escalate confirmed leads."
        ),
    },
    "blue-team/incident-response": {
        "how_it_works": (
            "Incident response (IR) is the structured process of **detecting, containing, "
            "eradicating, and recovering** from security incidents while preserving evidence. "
            "NIST SP 800-61 phases:\n\n"
            "1. **Preparation** — Playbooks, contacts, tooling, and tabletop exercises.\n"
            "2. **Detection & Analysis** — Triage alerts, determine scope and severity.\n"
            "3. **Containment** — Short-term (isolate host) and long-term (block IoCs, "
            "disable accounts).\n"
            "4. **Eradication** — Remove malware, close vulnerabilities, reset credentials.\n"
            "5. **Recovery** — Restore systems from clean backups; monitor for re-entry.\n"
            "6. **Post-incident** — Root cause analysis, lessons learned, control improvements.\n\n"
            "IR teams balance **speed** (stop bleeding) with **forensic integrity** (chain of "
            "custody for potential legal action)."
        ),
        "exploitation": (
            "1. **Activate playbook** — Declare severity (P1–P4); assign incident commander, "
            "scribe, and comms lead.\n"
            "2. **Preserve evidence** — Snapshot VMs, collect EDR triage packages, export "
            "relevant SIEM logs before containment alters state.\n"
            "3. **Scope the incident** — Identify compromised accounts, hosts, and data accessed; "
            "build timeline.\n"
            "4. **Contain** — Network isolate endpoints, disable AD accounts, revoke tokens "
            "and API keys.\n"
            "5. **Eradicate** — Reimage workstations, patch exploited vulnerability, remove "
            "persistence (scheduled tasks, registry, golden ticket requires krbtgt reset).\n"
            "6. **Recover** — Restore from known-good backups; validate integrity before "
            "reconnecting to network.\n"
            "7. **Communicate** — Stakeholder updates per cadence; legal/regulatory notification "
            "if PII/PHI affected.\n"
            "8. **Post-mortem** — Blameless review; track remediation items with owners and "
            "deadlines."
        ),
        "defense": (
            "- **Maintain IR playbooks** for ransomware, BEC, insider threat, and cloud compromise.\n"
            "- **Tabletop exercises** quarterly with executives and IT.\n"
            "- **Pre-position tooling** — EDR, forensic workstations, immutable backups, "
            "out-of-band comms.\n"
            "- **Define escalation matrix** — When to involve legal, PR, and law enforcement.\n"
            "- **Backup and restore testing** — Ransomware recovery depends on clean backups.\n"
            "- **Retainer with IR firm** — For surge capacity on P1 incidents.\n"
            "- **Track MTTR metrics** — Containment time, recovery time, repeat incident rate.\n"
            "- Follow [NIST SP 800-61 Rev. 2](https://csrc.nist.gov/publications/detail/sp/800-61/rev-2/final)."
        ),
    },
    "blue-team/malware-analysis": {
        "how_it_works": (
            "Malware analysis examines malicious software to understand **capabilities, "
            "persistence, C2 infrastructure, and indicators of compromise (IoCs)**. Two "
            "complementary approaches:\n\n"
            "- **Static analysis** — Inspect without execution: file hashes, strings, PE/ELF "
            "headers, imports, embedded resources, and disassembly (Ghidra, IDA).\n"
            "- **Dynamic analysis** — Execute in sandbox (ANY.RUN, Cuckoo, FLARE VM) and "
            "observe behavior: file writes, registry keys, network connections, process "
            "injection.\n\n"
            "Analysts classify malware families (ransomware, loader, RAT, infostealer) and "
            "extract IoCs (IPs, domains, file paths, mutexes, certificate thumbprints) for "
            "blocking and hunting. **Always work in isolated VMs** with no network route to "
            "production."
        ),
        "exploitation": (
            "1. **Set up isolated lab** — FLARE VM or custom VM with snapshots; host-only or "
            "simulated internet (INetSim).\n"
            "2. **Initial triage** — `sha256sum`, VirusTotal (cautious with uploads), `file`, "
            "`peframe`, `floss` for strings.\n"
            "3. **Static RE** — Load in Ghidra; identify `main`, C2 URL construction, and "
            "anti-analysis checks.\n"
            "4. **Dynamic run** — Execute in sandbox; capture Procmon, Wireshark, and "
            "API monitor output.\n"
            "5. **Unpack if needed** — Identify packers (UPX, custom); dump unpacked payload "
            "from memory.\n"
            "6. **Extract IoCs** — Domains, IPs, mutex names, registry persistence keys, "
            "dropped file hashes.\n"
            "7. **Document TTPs** — Map behaviors to MITRE ATT&CK; write YARA/Sigma from findings.\n"
            "8. **Share responsibly** — IoCs to ISACs and internal block lists; not public "
            "sample repos without policy approval."
        ),
        "defense": (
            "- **Block IoCs at perimeter** — Firewall, DNS, and proxy deny lists updated from "
            "analysis output.\n"
            "- **Deploy YARA on EDR** — Hunt for malware family signatures across endpoints.\n"
            "- **Sandbox inbound email attachments** — Detonate before delivery where feasible.\n"
            "- **Application allowlisting** — Block unsigned or unknown binaries on servers.\n"
            "- **Train analysts** — SANS FOR610 or equivalent; maintain lab environment.\n"
            "- **Retain samples securely** — Encrypted storage with access controls for "
            "re-analysis.\n"
            "- **Integrate with IR** — Malware analysis feeds directly into containment and "
            "eradication steps."
        ),
    },
}
